// desktop/src/plugins/site/Dashboard.vue
<template>
  <dashboard-layout>
    <group
     :title="$t(d.label)"
     :key="i"
     v-for="(d, i) in dashboard">
    <cell
      :key="j"
      :link="{name: l.href}"
      :title="$t(l.href + '.title')"
      v-for="(l, j) in d.items"/>
    </group>
  </dashboard-layout>
</template>

<script>
import { mapState } from 'vuex'
import { Cell, CellBox, Group, Badge } from 'vux'
import plugins from '@/plugins'

export default {
  components: {
    Group,
    Cell,
    CellBox,
    Badge
  },
  data () {
    return {
      showPanels: {}
    }
  },
  computed: {
    ...mapState({
      user: state => state.currentUser
    }),
    dashboard () {
      return plugins.dashboard(this.user)
    }
  }
}
</script>

// dashboard/src/plugins/site/Dashboard.jsx
import React from 'react'
import PropTypes from 'prop-types'
import {Row, Col, Card, Icon} from 'antd'
import {Link} from 'react-router-dom'
import i18n from 'i18next'
import { connect } from 'react-redux'

import plugins from '../../plugins'
import Layout from '../../layouts/Dashboard'

const Widget = ({user}) => (
  <Layout breadcrumb={[]}>
    <Row gutter={16}>
      {plugins.dashboard(user).map((d, i)=>{
        return (<Col span={8} key={i}>
          <Card title={<span><Icon type={d.icon} /> {i18n.t(d.label)}</span>}>
            {d.items.map((l, j) => (<p key={j}><Link to={l.href}>{i18n.t(l.label)}</Link></p>))}
          </Card>
        </Col>)
      })}
    </Row>
  </Layout>
)


Widget.propTypes = {
  user: PropTypes.object.isRequired,
}


export default connect(
  state => ({user: state.currentUser}),
  {},
)(Widget)
