// dashboard/src/plugins/site/Dashboard.vue
<template>
  <dashboard-layout>
    <el-col :md="{span: 8}" :key="i" v-for="(d, i) in dashboard"  style="padding: 16px;">
      <el-card>
        <div slot="header">
          {{$t(d.label)}}
        </div>
        <ul class="list-group">
          <li :key="j" v-for="(l, j) in d.items">
            <router-link :to="{name: l.href}">
              {{$t(`${l.href}.title`)}}
            </router-link>
          </li>
        </ul>
      </el-card>
    </el-col>
  </dashboard-layout>
</template>

<script>
import plugins from '@/plugins'

export default {
  data () {
    return {
    }
  },
  computed: {
    dashboard () {
      return plugins.dashboard(this.$store.state.currentUser)
    }
  }
}
</script>

// dashboard/src/plugins/site/Dashboard.jsx
import React from 'react'
import PropTypes from 'prop-types'
import {Row, Col, Card, Icon} from 'antd'
import {Link} from 'react-router-dom'
import i18n from 'i18next'
import { connect } from 'react-redux'

import plugins from '../../plugins'
import Layout from '../../layouts/Dashboard'

const Widget = ({user}) => (
  <Layout breadcrumb={[]}>
    <Row gutter={16}>
      {plugins.dashboard(user).map((d, i)=>{
        return (<Col span={8} key={i}>
          <Card title={<span><Icon type={d.icon} /> {i18n.t(d.label)}</span>}>
            {d.items.map((l, j) => (<p key={j}><Link to={l.href}>{i18n.t(l.label)}</Link></p>))}
          </Card>
        </Col>)
      })}
    </Row>
  </Layout>
)


Widget.propTypes = {
  user: PropTypes.object.isRequired,
}


export default connect(
  state => ({user: state.currentUser}),
  {},
)(Widget)
