// desktop/src/components/Header.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types'
import { Layout, Menu } from 'antd';
import {FormattedMessage} from 'react-intl'
import { connect } from 'react-redux'
import { push } from 'react-router-redux'

import {signOut} from '../actions'

const { Header } = Layout;

class Widget extends Component {
  handleMenu = ({key}) => {
    const {push} = this.props
    push(key)
  }
  render() {
    const {info, user} = this.props
    return (
      <Header className="header my-nowrap">
        <div className="logo" />
        <Menu
          theme="dark"
          mode="horizontal"
          onClick={this.handleMenu}
          defaultSelectedKeys={[]}
          style={{ lineHeight: '64px' }}
        >
          <Menu.Item key="to-/">{info.subTitle}</Menu.Item>
          {info.links.filter((l)=>l.loc === 'header').map((l,i)=><Menu.Item key={l.href}><FormattedMessage id={l.label}/></Menu.Item>)}
          {
            user.uid ?
              <Menu.Item key="/dashboard"><FormattedMessage id="site.dashboard.title"/></Menu.Item> :
              <Menu.Item key="/users/sign-in"><FormattedMessage id="auth.users.sign-in.title"/></Menu.Item>
          }
        </Menu>
      </Header>
    );
  }
}


Widget.propTypes = {
  push: PropTypes.func.isRequired,
  signOut: PropTypes.func.isRequired,
  user: PropTypes.object.isRequired,
  info: PropTypes.object.isRequired,
}


export default connect(
  state => ({
    user: state.currentUser,
    info: state.siteInfo,
  }),
  {push, signOut},
)(Widget)

// by-vue/src/components/Header.vue
<template>
  <el-menu theme="dark" mode="horizontal" @select="handleSelect">
    <el-menu-item index="to-site.home">{{$t("site.subTitle")}}</el-menu-item>
    <el-menu-item :index="`open-${l.href}`" :key="`open-header-${i}`" v-for="(l, i) in info.links.filter((l) => l.loc==='header')">{{$t(l.label)}}</el-menu-item>
    <LanguageBar />
    <PersonalBar />
  </el-menu>
</template>

<script>
import PersonalBar from './PersonalBar'
import LanguageBar from './LanguageBar'

export default {
  data () {
    return {
    }
  },
  components: {
    PersonalBar,
    LanguageBar
  },
  methods: {
    handleSelect (key, keyPath) {
      const to = 'to-'
      if (key.startsWith(to)) {
        this.$router.push({name: key.substring(to.length)})
        return
      }
      const open = 'open-'
      if (key.startsWith(open)) {
        window.open(key.substring(open.length), '_blank')
        return
      }
    }
  },
  computed: {
    info () {
      return this.$store.state.siteInfo
    }
  }
}
</script>
