// desktop/src/plugins/auth/users/Logs.jsx
import React, { Component } from 'react'
import { Table, Row, Col, message } from 'antd'
import {FormattedMessage} from 'react-intl'

import Layout from '../../../layouts/Dashboard'
import {get} from '../../../ajax'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/users/logs').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    const columns = [
      {
        title: <FormattedMessage id="attributes.createdAt"/>,
        dataIndex: 'createdAt',
        key: 'createdAt',
      },
      {
        title: 'IP',
        dataIndex: 'ip',
        key: 'ip',
      },
      {
        title: <FormattedMessage id="attributes.content"/>,
        dataIndex: 'message',
        key: 'message',
      }
    ]

    return (
      <Layout breads={[{href: '/users/logs', label: 'auth.users.logs.title'}]}>
        <Row>
          <Col>
            <Table bordered rowKey="id" columns={columns} dataSource={this.state.items} />
          </Col>
        </Row>
      </Layout>
    );
  }
}

export default Widget

// mobile/src/plugins/auth/users/Logs.vue
<template>
  <dashboard-layout>
    <x-table full-bordered>
      <thead>
        <tr>
          <th>{{$t('attributes.createdAt')}}</th>
          <th>IP</th>
          <th>{{$t('attributes.content')}}</th>
        </tr>
      </thead>
      <tbody>
        <tr :key="i" v-for="(l, i) in items">
          <td>{{l.createdAt}}</td>
          <td>{{l.ip}}</td>
          <td>{{l.message}}</td>
        </tr>
      </tbody>
    </x-table>
  </dashboard-layout>
</template>

<script>
import { XTable } from 'vux'
import {get, fail} from '@/ajax'

export default {
  components: {
    XTable
  },
  created () {
    get('/users/logs').then((rst) => { this.items = rst }).catch((err) => fail(this, err))
  },
  data () {
    return {
      items: []
    }
  }
}
</script>
