// by-antd/src/plugins/auth/users/ChangePassword.jsx
import React, { Component } from 'react';
import { Form, Input, message } from 'antd';
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'

import Layout from '../../../layouts/Dashboard'
import {formItemLayout} from '../../../constants'
import SubmitButton from '../../../components/SubmitButton'
import {post} from '../../../ajax'

const FormItem = Form.Item;

class WidgetF extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    const {formatMessage} = this.props.intl
    const {setFieldsValue, validateFieldsAndScroll} = this.props.form
    validateFieldsAndScroll((err, values) => {
     if (!err) {
       post('/users/change-password', values)
        .then((rst) => {
          message.success(formatMessage({id: 'messages.success'}))
          setFieldsValue({currentPassword: '', newPassword: '', passwordConfirmation: ''})
        }).catch(message.error)
     }
    });
  }
  checkPasswords = (rule, value, callback) => {
    const {formatMessage} = this.props.intl
    const form = this.props.form;
    if (value && value !== form.getFieldValue('newPassword')) {
      callback(formatMessage({id: "errors.passwordConfirmation"}));
    } else {
      callback();
    }
  }
  render() {
    const {formatMessage} = this.props.intl
    const { getFieldDecorator } = this.props.form;
    return (
      <Layout breads={[{href: '/users/change-password', label: 'auth.users.change-password.title'}]}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.currentPassword"/>}
            hasFeedback
          >
          {getFieldDecorator('currentPassword', {
            rules: [
              { required: true, message: formatMessage({id:"errors.not-empty"})},
            ],
          })(
            <Input type="password" />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.newPassword"/>}
            hasFeedback
          >
          {getFieldDecorator('newPassword', {
            rules: [
              { required: true, min: 6, max: 32, message: formatMessage({id:"errors.password"})},
            ],
          })(
            <Input type="password" />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.passwordConfirmation"/>}
            hasFeedback
          >
          {getFieldDecorator('passwordConfirmation', {
            rules: [
              { required: true, message: formatMessage({id:"errors.not-empty"})},
              {validator: this.checkPasswords},
            ],
          })(
            <Input type="password" />
          )}
          </FormItem>
          <SubmitButton />
        </Form>
      </Layout>
    );
  }
}

WidgetF.propTypes = {
  intl: intlShape.isRequired,
}

export default Form.create()(injectIntl(WidgetF))

// fly/src/plugins/auth/users/ChangePassword.vue
<template>
  <dashboard-layout title="auth.users.change-password.title">
    <el-col :md="{span:16, offset:1}">
      <el-form ref="form" :model="form" :rules="rules" label-width="80px">
        <el-form-item :label="$t('attributes.currentPassword')" prop="currentPassword">
          <el-input type="password" v-model="form.currentPassword" />
        </el-form-item>
        <el-form-item :label="$t('attributes.newPassword')" prop="newPassword">
          <el-input type="password" v-model="form.newPassword" />
        </el-form-item>
        <el-form-item :label="$t('attributes.passwordConfirmation')" prop="passwordConfirmation">
          <el-input type="password" v-model="form.passwordConfirmation" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        </el-form-item>
      </el-form>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  data () {
    return {
      form: {
        currentPassword: '',
        newPassword: '',
        passwordConfirmation: ''
      }
    }
  },
  computed: {
    rules () {
      var password2 = (rule, value, callback) => {
        if (value !== this.form.newPassword) {
          callback(new Error(this.$i18n.t('helpers.passwordConfirmation')))
        } else {
          callback()
        }
      }
      return {
        currentPassword: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        newPassword: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' },
            { min: 6, max: 32, message: this.$t('helpers.password'), trigger: 'change' }
        ],
        passwordConfirmation: [
          { required: true, message: this.$i18n.t('helpers.not-empty'), trigger: 'change' },
          { validator: password2, trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/users/change-password', this.form)
            .then(function (rst) {
              this.$message.success(this.$t('success'))
              this.$refs[formName].resetFields()
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    }
  }
}
</script>
