// desktop/src/plugins/auth/users/Logs.jsx
import React, { Component } from 'react'
import { Table, Row, Col, message } from 'antd'
import {FormattedMessage} from 'react-intl'

import Layout from '../../../layouts/Dashboard'
import {get} from '../../../ajax'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/users/logs').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    const columns = [
      {
        title: <FormattedMessage id="attributes.createdAt"/>,
        dataIndex: 'createdAt',
        key: 'createdAt',
      },
      {
        title: 'IP',
        dataIndex: 'ip',
        key: 'ip',
      },
      {
        title: <FormattedMessage id="attributes.content"/>,
        dataIndex: 'message',
        key: 'message',
      }
    ]

    return (
      <Layout breads={[{href: '/users/logs', label: 'auth.users.logs.title'}]}>
        <Row>
          <Col>
            <Table bordered rowKey="id" columns={columns} dataSource={this.state.items} />
          </Col>
        </Row>
      </Layout>
    );
  }
}

export default Widget

// fly/src/plugins/auth/users/Logs.vue
<template>
  <dashboard-layout title="auth.users.logs.title">
    <el-col :md="{span: 22, offset: 1}">
      <el-table :data="items" border stripe style="width: 100%">
        <el-table-column width="240" prop="createdAt" :label="$t('attributes.createdAt')" />
        <el-table-column width="120" prop="ip" label="IP" />
        <el-table-column prop="message" :label="$t('auth.attributes.log.message')" />
      </el-table>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get} from '@/ajax'

export default {
  created () {
    get('/users/logs').then((rst) => { this.items = rst }).catch(this.$message.error)
  },
  data () {
    return {
      items: []
    }
  }
}
</script>
