// dashboard/src/plugins/auth/users/ResetPassword.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { Form } from 'semantic-ui-react'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'

import Layout from '../NonSignIn'
import {Submit} from '../../../form'
import {post} from '../../../ajax'

class Widget extends Component{
  state = { password: '', passwordConfirmation: '' }

  handleChange = (e, { name, value }) => this.setState({ [name]: value })

  handleSubmit = e => {
    e.preventDefault()
    const {push, match} = this.props
    var data = new URLSearchParams()
    data.append('token', match.params.token)
    data.append('password', this.state.password)
    data.append('passwordConfirmation', this.state.passwordConfirmation)
    post('/users/reset-password', data).then((rst) => {
      alert(rst.message)
      push('/users/sign-in')
    }).catch(alert)
  }
  render() {
    const {password, passwordConfirmation} = this.state;
    return (
      <Layout title="auth.users.reset-password.title">
        <Form onSubmit={this.handleSubmit}>
          <Form.Input name='password' value={password} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.password"/>} />
          <Form.Input name='passwordConfirmation' value={passwordConfirmation} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.passwordConfirmation"/>} />
          <Submit />
        </Form>
      </Layout>
    )
  }
}


Widget.propTypes = {
  push: PropTypes.func.isRequired
}


export default connect(
  state => ({}),
  {push},
)(Widget)

// fly/src/plugins/auth/users/ResetPassword.vue
<template>
  <non-sign-in-layout title="auth.users.reset-password.title">
    <form>
      <div class="form-group">
        <label>{{$t('attributes.password')}}</label>
        <b-form-input v-model="password" type="password"/>
        <small class="form-text text-muted">{{$t('helpers.password')}}</small>
      </div>
      <div class="form-group">
        <label>{{$t('attributes.passwordConfirmation')}}</label>
        <b-form-input v-model="passwordConfirmation" type="password"/>
        <small class="form-text text-muted">{{$t('helpers.passwordConfirmation')}}</small>
      </div>
      <b-button v-on:click="onSubmit" variant="primary">{{$t('buttons.submit')}}</b-button>
    </form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  data () {
    return {
      password: '',
      passwordConfirmation: ''
    }
  },
  methods: {
    onSubmit (e) {
      e.preventDefault()
      var data = new URLSearchParams()
      data.append('token', this.$route.params.token)
      data.append('password', this.password)
      data.append('passwordConfirmation', this.passwordConfirmation)
      post('/users/reset-password', data)
        .then(function (rst) {
          alert(this.$t('auth.messages.reset-password-success'))
          this.$router.push({name: 'auth.users.sign-in'})
        }.bind(this)).catch(alert)
    }
  }
}
</script>
