// by-react/src/plugins/auth/users/EmailForm.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'
import { Form, Input, message} from 'antd'
import i18n from 'i18next'

import Layout from '../NonSignIn'
import {Submit, formItemLayout} from '../../../form'
import {post} from '../../../ajax'

const FormItem = Form.Item

class WidgetF extends Component {  
  handleSubmit = (e) => {
    e.preventDefault();
    const {push, action} = this.props
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        post(`/users/${action}`, values).then((rst) => {
          message.success(i18n.t(`auth.messages.email-for-${action}`));
          push('/users/sign-in')
        }).catch(message.error)
      }
    });
  }

  render() {
    const { action } = this.props
    const { getFieldDecorator } = this.props.form;

    return (
    <Layout href={`/users/${action}`} title={`auth.users.${action}.title`}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem
          {...formItemLayout}
          label={i18n.t('attributes.email')}
          hasFeedback
        >
          {getFieldDecorator('email', {
            rules: [{
              type: 'email', message: i18n.t('helpers.bad-email'),
            }, {
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <Submit />
      </Form>
    </Layout>
    );
  }
}

WidgetF.propTypes = {
  push: PropTypes.func.isRequired,
  action: PropTypes.string.isRequired,
}

const Widget = Form.create()(WidgetF);

export default connect(
  state => ({}),
  {push},
)(Widget)

// dashboard/src/plugins/auth/users/EmailForm.vue
<template>
  <non-sign-in-layout :title="`auth.users.${action}.title`">
    <el-form ref="form" :model="form" :rules="rules" label-width="80px">
      <el-form-item :label="$t('attributes.email')" prop="email">
        <el-input v-model="form.email" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        <el-button @click="resetForm('form')">{{$t("buttons.reset")}}</el-button>
      </el-form-item>
    </el-form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  props: ['action'],
  data () {
    return {
      form: {
        email: ''
      }
    }
  },
  computed: {
    rules () {
      return {
        email: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' },
          { type: 'email', message: this.$t('helpers.bad-email'), trigger: 'change' }
        ],
        password: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post(`/users/${this.action}`, this.form)
            .then(
              function (rst) {
                this.$message.success(this.$t(`auth.messages.email-for-${this.action}`))
                this.$router.push({name: 'auth.users.sign-in'})
              }.bind(this)
            ).catch(this.$message.error)
        } else {
          return false
        }
      })
    },
    resetForm (formName) {
      this.$refs[formName].resetFields()
    }
  }
}
</script>
