// fly/src/plugins/auth/users/EmailForm.vue
<template>
  <non-sign-in-layout :title="`auth.users.${action}.title`">
    <form>
      <div class="form-group">
        <label for="email">{{$t('attributes.email')}}</label>
        <b-form-input v-model="email" type="email" />
      </div>
      <b-button v-on:click="onSubmit" variant="primary">{{$t('buttons.submit')}}</b-button>
    </form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  props: ['action'],
  data () {
    return {
      email: ''
    }
  },
  methods: {
    onSubmit (e) {
      e.preventDefault()
      var data = new URLSearchParams()
      data.append('email', this.email)
      post(`/users/${this.action}`, data)
        .then(
          function (rst) {
            alert(this.$t(`auth.messages.email-for-${this.action}`))
            this.$router.push({name: 'auth.users.sign-in'})
          }.bind(this)
        ).catch(alert)
    }
  }
}
</script>

// dashboard/src/plugins/auth/users/EmailForm.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { Form } from 'semantic-ui-react'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'

import Layout from '../NonSignIn'
import {Submit} from '../../../form'
import {post} from '../../../ajax'

class Widget extends Component{
  state = { email: '' }

  handleChange = (e, { name, value }) => this.setState({ [name]: value })

  handleSubmit = e => {
    e.preventDefault()
    const {push, action} = this.props
    var data = new URLSearchParams()
    data.append('email',this.state.email)
    post(`/users/${action}`, data).then((rst) => {
      alert(rst.message)
      push('/users/sign-in')
    }).catch(alert)
  }
  render() {
    const {email} = this.state;
    const {action} = this.props;
    return (
      <Layout title={`auth.users.${action}.title`}>
        <Form onSubmit={this.handleSubmit}>
          <Form.Input name='email' value={email} onChange={this.handleChange} required type="email" label={<FormattedMessage id="attributes.email"/>} />
          <Submit />
        </Form>
      </Layout>
    )
  }
}


Widget.propTypes = {
  push: PropTypes.func.isRequired,
  action: PropTypes.string.isRequired,
}


export default connect(
  state => ({}),
  {push},
)(Widget)
