// dashboard/src/plugins/auth/users/SignIn.vue
<template>
  <div>
    <group label-width="4.5em" label-margin-right="2em" label-align="right">
      <x-input
        :title="$t('attributes.email')"
        :placeholder="$t('placeholders.email')"
        v-model="form.email" />
      <x-input
        type="password"
        :title="$t('attributes.password')"
        :placeholder="$t('placeholders.password')"
        v-model="form.password" />
    </group>
    <box gap="10px 10px">
      <x-button type="primary" @click.native="submitForm">{{$t("buttons.submit")}}</x-button>
    </box>
  </div>
</template>

<script>
import { Group, Box, XInput, XButton } from 'vux'
import { mapActions } from 'vuex'
import { post, fail, success } from '@/ajax'
import { TOKEN } from '@/constants'

export default {
  components: {
    Group,
    XInput,
    XButton,
    Box
  },
  data () {
    return {
      form: {
        email: '',
        password: ''
      }
    }
  },
  methods: {
    ...mapActions([
      'signIn'
    ]),
    submitForm () {
      let that = this
      post('/users/sign-in', this.form)
      .then(rst => {
        var token = rst.token
        sessionStorage.setItem(TOKEN, token)
        that.signIn(token)
        that.$router.push({name: 'site.dashboard'})
        success(that)
      })
      .catch(err => fail(that, err))
    }
  }
}
</script>

// dashboard/src/plugins/auth/users/SignIn.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { Form } from 'semantic-ui-react'
import { FormattedMessage } from 'react-intl'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'

import Layout from '../NonSignIn'
import {Submit} from '../../../form'
import {post} from '../../../ajax'
import {signIn} from '../../../actions'
import {TOKEN} from '../../../constants'

class Widget extends Component{
  state = { email: '', password: '' }

  handleChange = (e, { name, value }) => this.setState({ [name]: value })

  handleSubmit = e => {
    e.preventDefault()
    const {push, signIn} = this.props
    var data = new URLSearchParams()
    data.append('email',this.state.email)
    data.append('password',this.state.password)
    post('/users/sign-in', data).then((rst) => {
      sessionStorage.setItem(TOKEN, rst.token)
      signIn(rst.token)
      push('/dashboard')
    }).catch(alert)
  }
  render() {
    const { email, password} = this.state;
    return (
      <Layout title="auth.users.sign-in.title">
        <Form onSubmit={this.handleSubmit}>
          <Form.Input name='email' value={email} onChange={this.handleChange} required type="email" label={<FormattedMessage id="attributes.email"/>} />
          <Form.Input name='password' value={password} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.password"/>} />
          <Submit />
        </Form>
      </Layout>
    )
  }
}


Widget.propTypes = {
  push: PropTypes.func.isRequired,
  signIn: PropTypes.func.isRequired
}


export default connect(
  state => ({}),
  {push, signIn},
)(Widget)
