// fly/src/plugins/auth/users/SignUp.vue
<template>
  <non-sign-in-layout title="auth.users.sign-up.title">
    <form>
      <div class="form-group">
        <label>{{$t('attributes.fullName')}}</label>
        <b-form-input v-model="name" type="text"/>
      </div>
      <div class="form-group">
        <label for="email">{{$t('attributes.email')}}</label>
        <b-form-input v-model="email" type="email"/>
        <small class="form-text text-muted">{{$t('helpers.email')}}</small>
      </div>
      <div class="form-group">
        <label>{{$t('attributes.password')}}</label>
        <b-form-input v-model="password" type="password"/>
        <small class="form-text text-muted">{{$t('helpers.password')}}</small>
      </div>
      <div class="form-group">
        <label>{{$t('attributes.passwordConfirmation')}}</label>
        <b-form-input v-model="passwordConfirmation" type="password"/>
        <small class="form-text text-muted">{{$t('helpers.passwordConfirmation')}}</small>
      </div>
      <b-button v-on:click="onSubmit" variant="primary">{{$t('buttons.submit')}}</b-button>
    </form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  data () {
    return {
      name: '',
      email: '',
      password: '',
      passwordConfirmation: ''
    }
  },
  methods: {
    onSubmit (e) {
      e.preventDefault()
      var data = new URLSearchParams()
      data.append('email', this.email)
      data.append('name', this.name)
      data.append('password', this.password)
      data.append('passwordConfirmation', this.passwordConfirmation)
      post('/users/sign-up', data)
        .then(function (rst) {
          alert(this.$t('auth.messages.email-for-confirm'))
          this.$router.push({name: 'auth.users.sign-in'})
        }.bind(this)).catch(alert)
    }
  }
}
</script>

// dashboard/src/plugins/auth/users/SignUp.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { Form } from 'semantic-ui-react'
import { FormattedMessage } from 'react-intl'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'

import Layout from '../NonSignIn'
import {Submit} from '../../../form'
import {post} from '../../../ajax'

class Widget extends Component{
  state = { name: '', email: '', password: '', passwordConfirmation: '' }

  handleChange = (e, { name, value }) => this.setState({ [name]: value })

  handleSubmit = e => {
    e.preventDefault()
    const {push} = this.props
    var data = new URLSearchParams()
    data.append('name',this.state.name)
    data.append('email',this.state.email)
    data.append('password',this.state.password)
    data.append('passwordConfirmation',this.state.passwordConfirmation)
    post('/users/sign-up', data).then((rst) => {
      alert(rst.message)
      push('/users/sign-in')
    }).catch(alert)
  }
  render() {
    const {name, email, password, passwordConfirmation} = this.state;
    return (
      <Layout title="auth.users.sign-up.title">
        <Form onSubmit={this.handleSubmit}>
          <Form.Input name='name' value={name} onChange={this.handleChange} required label={<FormattedMessage id="attributes.fullName"/>} />
          <Form.Input name='email' value={email} onChange={this.handleChange} required type="email" label={<FormattedMessage id="attributes.email"/>} />
          <Form.Input name='password' value={password} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.password"/>} />
          <Form.Input name='passwordConfirmation' value={passwordConfirmation} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.passwordConfirmation"/>} />
          <Submit />
        </Form>
      </Layout>
    )
  }
}


Widget.propTypes = {
  push: PropTypes.func.isRequired
}


export default connect(
  state => ({}),
  {push},
)(Widget)
