// by-antd/src/plugins/site/admin/locales/Index.jsx
import React, { Component } from 'react'
import { Table, Row, Col, Button, Popconfirm, message } from 'antd'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'


import Layout from '../../../../layouts/Dashboard'
import {get, _delete} from '../../../../ajax'

class WidgetF extends Component {
  state = { items: []}
  componentDidMount () {
    get('/admin/locales').then(
      function (rst){
        this.setState({items: Object.entries(rst).map((v)=>({code:v[0], message:v[1]}))})
      }.bind(this)
    ).catch(message.error)
  }
  handleRemove = (code) => {
    const {formatMessage} = this.props.intl
    _delete(`/admin/locales/${code}`)
      .then((rst)=>{
        message.success(formatMessage({id: 'messages.success'}))
        var items = this.state.items.filter((it) => it.code !== code)
        this.setState({items})
      })
      .catch(message.error)
  }
  render() {
    const {push} = this.props
    const columns = [
      {
        title: <FormattedMessage id="site.attributes.locale.code"/>,
        dataIndex: 'code',
        key: 'code',
      },
      {
        title: <FormattedMessage id="site.attributes.locale.message"/>,
        dataIndex: 'message',
        key: 'message',
      },
      {
        title: <FormattedMessage id="buttons.manage"/>,
      key: 'manage',
        render: (text, record) =>(<span>
          <Button onClick={(e)=>push(`/admin/locales/edit/${record.code}`)} shape="circle" icon="edit" />
          <Popconfirm title={<FormattedMessage id="messages.are-you-sure"/>} onConfirm={(e) => this.handleRemove(record.code)}>
            <Button type="danger" shape="circle" icon="delete" />
          </Popconfirm>
        </span>)
      },
    ]

    return (
      <Layout admin breads={[{href: '/admin/locales', label: 'site.admin.locales.index.title'}]}>
        <Row>
          <Col>
            <Button onClick={(e)=>push('/admin/locales/new')} type='primary' shape="circle" icon="plus" />
            <Table bordered rowKey="code" columns={columns} dataSource={this.state.items} />
          </Col>
        </Row>
      </Layout>
    );
  }
}



WidgetF.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired,
}

const Widget = injectIntl(WidgetF)

export default connect(
  state => ({}),
  {push},
)(Widget)

// desktop/src/plugins/site/admin/locales/Index.vue
<template>
  <dashboard-layout admin>
    <x-table full-bordered>
      <thead>
        <tr>
          <th>{{$t('site.attributes.locale.code')}}</th>
          <th>{{$t('site.attributes.locale.message')}}</th>
          <th width="60px">
            {{$t('buttons.manage')}}
            <router-link :to="{name: 'site.admin.locales.new'}"><fa-icon name="plus"/></router-link>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr :key="i" v-for="(l, i) in items">
          <td>{{l.code}}</td>
          <td>{{l.message}}</td>
          <td>
            <router-link :to="{name: 'site.admin.locales.edit', params: {code: l.code}}">
              <fa-icon name="pencil"/>
            </router-link>
            <fa-icon @click.native="onRemove(l.code)" name="trash"/>
          </td>
        </tr>
      </tbody>
    </x-table>
  </dashboard-layout>
</template>

<script>
import { XTable } from 'vux'
import {get, fail, destroy} from '@/ajax'

export default {
  components: {
    XTable
  },
  created () {
    get('/admin/locales').then((rst) => { this.items = Object.entries(rst).map((v) => { return { code: v[0], message: v[1] } }) }).catch((err) => fail(this, err))
  },
  data () {
    return {
      items: []
    }
  },
  methods: {
    onRemove (code) {
      destroy(this, `/admin/locales/${code}`, (rst) => {
        this.items = this.items.filter((l) => l.code !== code)
      })
    }
  }
}
</script>
