// by-react/src/plugins/site/admin/Locales.jsx
import React, {Component} from 'react'
import i18n from 'i18next'
import {Row, Col, Table, Button, Modal, message} from 'antd'

import Layout from '../../../layouts/Dashboard'
import {get, _delete, post} from '../../../ajax'

const confirm = Modal.confirm

class Widget extends Component{
  state = { items: []}
  componentDidMount () {
    get('/admin/locales').then(
      function (rst){
        this.setState({
          items: Object.entries(rst).map(
            (v)=>{return {code:v[0], message:v[1]} }
          )},
        )
      }.bind(this)
    )
  }
  onDelete(code){
    confirm({
      title: i18n.t('are-you-sure'),
      onOk: function() {
        _delete(`/admin/locales/${code}`).then(function(rst){
          const items = [...this.state.items]
          this.setState({ items: items.filter((o)=>o.code !== code) });
        }.bind(this)).catch(message.error)        
      }.bind(this)
    });
  }
  onEdit(code){

  }
  render () {
    const columns = [
      {
        title: i18n.t('site.attributes.locale.code'),
        dataIndex: 'code',
        key: 'code',
      },
      {
        title: i18n.t('site.attributes.locale.message'),
        dataIndex: 'message',
        key: 'message',
      },
      {
        title: i18n.t('buttons.manage'),
        key: 'manage',
         render: (text, record) => (<span>
           <Button onClick={()=>this.onEdit(record.code)} size="small" shape="circle" icon="edit" />
           <Button onClick={()=>this.onDelete(record.code)} size="small" shape="circle" icon="delete" type="danger" />
         </span>)
      },
    ]

    return (
      <Layout breadcrumb={[{label: 'site.admin.locales.index.title', href: '/admin/locales'}]}>
        <Row>
          <Col xs={{span: 24}} sm={{offset:1, span:22}}>
            <Button style={{ marginBottom: '8px'}}>{i18n.t('buttons.new')}</Button>
            <Table bordered rowKey="code" columns={columns} dataSource={this.state.items} />
          </Col>
        </Row>
      </Layout>
    )
  }
}

export default Widget

// desktop/src/plugins/site/admin/locales/Index.vue
<template>
  <dashboard-layout admin>
    <x-table full-bordered>
      <thead>
        <tr>
          <th>{{$t('site.attributes.locale.code')}}</th>
          <th>{{$t('site.attributes.locale.message')}}</th>
          <th width="60px">
            {{$t('buttons.manage')}}
            <router-link :to="{name: 'site.admin.locales.new'}"><fa-icon name="plus"/></router-link>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr :key="i" v-for="(l, i) in items">
          <td>{{l.code}}</td>
          <td>{{l.message}}</td>
          <td>
            <router-link :to="{name: 'site.admin.locales.edit', params: {code: l.code}}">
              <fa-icon name="pencil"/>
            </router-link>
            <fa-icon @click.native="onRemove(l.code)" name="trash"/>
          </td>
        </tr>
      </tbody>
    </x-table>
  </dashboard-layout>
</template>

<script>
import { XTable } from 'vux'
import {get, fail, destroy} from '@/ajax'

export default {
  components: {
    XTable
  },
  created () {
    get('/admin/locales').then((rst) => { this.items = Object.entries(rst).map((v) => { return { code: v[0], message: v[1] } }) }).catch((err) => fail(this, err))
  },
  data () {
    return {
      items: []
    }
  },
  methods: {
    onRemove (code) {
      destroy(this, `/admin/locales/${code}`, (rst) => {
        this.items = this.items.filter((l) => l.code !== code)
      })
    }
  }
}
</script>
