// dashboard/src/plugins/site/admin/site/Status.vue
<template>
  <dashboard-layout title="site.admin.status.title" admin>
    <group :title="$t('site.admin.status.title')">
      <cell
      is-link
      :border-intent="false"
      :arrow-direction="show.os ? 'up' : 'down'"
      @click.native="show.os = !show.os">
        <span slot="title">
          {{$t('site.admin.status.os')}}
          <badge :text="item.os.length" />
        </span>
      </cell>
      <template v-if="show.os">
        <cell-box :key="i" v-for="(v, i) in item.os">
          {{v.key}}: {{v.val}}
        </cell-box>
      </template>

      <cell
        is-link
        :border-intent="false"
        :arrow-direction="show.database ? 'up' : 'down'"
        @click.native="show.database = !show.database">
        <span slot="title">
          {{$t('site.admin.status.database')}}
          <badge :text="item.database.length" />
        </span>
      </cell>
      <template v-if="show.database">
        <cell-box :key="i" v-for="(v, i) in item.database">
          {{v.key}}: {{v.val}}
        </cell-box>
      </template>

      <cell
        is-link
        :border-intent="false"
        :arrow-direction="show.network ? 'up' : 'down'"
        @click.native="show.network = !show.network">
        <span slot="title">
          {{$t('site.admin.status.network')}}
          <badge :text="item.network.length" />
        </span>
      </cell>
      <template v-if="show.network">
        <cell-box :key="i" v-for="(v, i) in item.network">
          {{v.key}}: {{v.val}}
        </cell-box>
      </template>


      <cell
        is-link
        :border-intent="false"
        :arrow-direction="show.jobs ? 'up' : 'down'"
        @click.native="show.jobs = !show.jobs">
        <span slot="title">
          {{$t('site.admin.status.jobs')}}
          <badge :text="item.jobs.length" />
        </span>
      </cell>
      <template v-if="show.jobs">
        <cell-box :key="i" v-for="(v, i) in item.jobs">
          {{v.key}}: {{v.val}}
        </cell-box>
      </template>


      <cell
        is-link
        :border-intent="false"
        :arrow-direction="show.cache ? 'up' : 'down'"
        @click.native="show.cache = !show.cache">
        <span slot="title">
          {{$t('site.admin.status.cache')}}
          <badge :text="item.cache.length" />
        </span>
      </cell>
      <template v-if="show.cache">
        <cell-box :key="i" v-for="(v, i) in item.cache">
          {{v}}
        </cell-box>
      </template>

      <cell
        is-link
        :border-intent="false"
        :arrow-direction="show.routes ? 'up' : 'down'"
      @click.native="show.routes = !show.routes">
        <span slot="title">
          {{$t('site.admin.status.routes')}}
          <badge :text="item.routes.length" />
        </span>
      </cell>
      <template v-if="show.routes">
        <cell-box :key="i" v-for="(v, i) in item.routes">
          {{v.method}} {{v.path}}
        </cell-box>
      </template>

    </group>
  </dashboard-layout>
</template>

<script>
import { Cell, CellBox, Group, Badge } from 'vux'

import {get, fail} from '@/ajax'

export default {
  components: {
    Cell,
    CellBox,
    Group,
    Badge
  },
  created () {
    get('/admin/site/status').then((rst) => {
      this.item.os = this.parse(rst.os)
      this.item.network = this.parse(rst.network)
      this.item.database = this.parse(rst.database)
      this.item.jobs = this.parse(rst.jobs)
      this.item.cache = rst.cache
      this.item.routes = rst.routes
    }).catch((err) => fail(this, err))
  },
  data () {
    return {
      show: {
        database: false,
        os: false,
        jobs: false,
        network: false,
        cache: false,
        routes: false
      },
      item: {
        database: {},
        os: {},
        jobs: {},
        network: {},
        cache: [],
        routes: []
      }
    }
  },
  methods: {
    parse (o) {
      return Object.entries(o).map((v, k) => {
        return {key: v[0], val: v[1]}
      })
    }
  }
}
</script>

// dashboard/src/plugins/site/admin/Status.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import i18n from 'i18next'
import {Row, Col, Card} from 'antd'

import Layout from '../../../layouts/Dashboard'
import {get} from '../../../ajax'

const Panel = ({name, value}) => (
  <Card title={i18n.t(`site.admin.status.${name}`)}>
    {Object.entries(value).map((v,i)=><p key={i}>{v[0]}: {v[1]}</p>)}
  </Card>
)

Panel.propTypes = {
  name: PropTypes.string.isRequired,
  value: PropTypes.object.isRequired,
}

class Widget extends Component{
  state = {
    database: {},
    os: {},
    network: {},
    jobs: {},
    routes: [],
    cache: [],
  }
  componentDidMount () {
    get('/admin/site/status').then(
      function (rst){
        this.setState(rst)
      }.bind(this)
    )
  }
  render () {
    return (
      <Layout breadcrumb={[{label: 'site.admin.status.title', href: '/admin/site/status'}]}>
        <Row gutter={16}>
          <Col span={24} className="my-gutter-box">
            <Panel name="os" value={this.state.os}/>
          </Col>
          <Col span={24} className="my-gutter-box">
            <Panel name="network" value={this.state.network}/>
          </Col>
          <Col span={24} className="my-gutter-box">
            <Panel name="database" value={this.state.database}/>
          </Col>
          <Col span={24} className="my-gutter-box">
            <Panel name="jobs" value={this.state.jobs}/>
          </Col>
          <Col xs={24} sm={12} className="my-gutter-box">
            <Card title={i18n.t('site.admin.status.cache')}>
              {this.state.cache.map((v,i)=><p key={i}>{v}</p>)}
            </Card>
          </Col>
          <Col xs={24} sm={12} className="my-gutter-box">
            <Card title={i18n.t('site.admin.status.routes')}>
              {this.state.routes.map((v,i)=><p key={i}>{v.method} {v.path}</p>)}
            </Card>
          </Col>
        </Row>
      </Layout>
    )
  }
}

export default Widget
