// fly/src/plugins/site/admin/Status.vue
<template>
  <dashboard-layout title="site.admin.status.title">
    <el-col :md="{span: 10, offset: 1}">
      <h4>{{$t('site.admin.status.routes')}}</h4>
      <el-table :data="item.routes" border stripe style="width: 100%">
        <el-table-column width="120" prop="method" label="HTTP METHOD" />
        <el-table-column prop="path" label="PATH" />
      </el-table>
    </el-col>
    <ItemPanel :value="item.os" action="os"/>
    <ItemPanel :value="item.network" action="network"/>
    <ItemPanel :value="item.database" action="database"/>
    <ItemPanel :value="item.jobs" action="jobs"/>
    <el-col :md="{span: 10, offset: 1}">
      <h4>{{$t('site.admin.status.cache')}}</h4>
      <el-table :data="item.cache.map((r) => { return {val: r} })" border stripe style="width: 100%">
        <el-table-column prop="val" label="VAL" />
      </el-table>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get} from '@/ajax'
import ItemPanel from './StatusItem'

export default {
  created () {
    get('/admin/site/status').then((rst) => { this.item = rst }).catch(this.$message.error)
  },
  data () {
    return {
      item: {
        database: {},
        os: {},
        jobs: {},
        network: {},
        cache: [],
        routes: []
      }
    }
  },
  components: {
    ItemPanel
  }
}
</script>

// dashboard/src/plugins/site/admin/Status.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import i18n from 'i18next'
import {Row, Col, Card} from 'antd'

import Layout from '../../../layouts/Dashboard'
import {get} from '../../../ajax'

const Panel = ({name, value}) => (
  <Card title={i18n.t(`site.admin.status.${name}`)}>
    {Object.entries(value).map((v,i)=><p key={i}>{v[0]}: {v[1]}</p>)}
  </Card>
)

Panel.propTypes = {
  name: PropTypes.string.isRequired,
  value: PropTypes.object.isRequired,
}

class Widget extends Component{
  state = {
    database: {},
    os: {},
    network: {},
    jobs: {},
    routes: [],
    cache: [],
  }
  componentDidMount () {
    get('/admin/site/status').then(
      function (rst){
        this.setState(rst)
      }.bind(this)
    )
  }
  render () {
    return (
      <Layout breadcrumb={[{label: 'site.admin.status.title', href: '/admin/site/status'}]}>
        <Row gutter={16}>
          <Col span={24} className="my-gutter-box">
            <Panel name="os" value={this.state.os}/>
          </Col>
          <Col span={24} className="my-gutter-box">
            <Panel name="network" value={this.state.network}/>
          </Col>
          <Col span={24} className="my-gutter-box">
            <Panel name="database" value={this.state.database}/>
          </Col>
          <Col span={24} className="my-gutter-box">
            <Panel name="jobs" value={this.state.jobs}/>
          </Col>
          <Col xs={24} sm={12} className="my-gutter-box">
            <Card title={i18n.t('site.admin.status.cache')}>
              {this.state.cache.map((v,i)=><p key={i}>{v}</p>)}
            </Card>
          </Col>
          <Col xs={24} sm={12} className="my-gutter-box">
            <Card title={i18n.t('site.admin.status.routes')}>
              {this.state.routes.map((v,i)=><p key={i}>{v.method} {v.path}</p>)}
            </Card>
          </Col>
        </Row>
      </Layout>
    )
  }
}

export default Widget
