// mobile/src/plugins/site/posts/Index.vue
<template>
  <group
    :title="$t('site.posts.index.title')"
  >
    <cell
      :key="i"
      :title="l.title"
      :link="{name: 'site.posts.show', params: {name: l.name}}"
      v-for="(l, i) in items"/>
  </group>
</template>

<script>
import { Group, Cell } from 'vux'
import { get, fail } from '@/ajax'

export default {
  components: {
    Group,
    Cell
  },
  data () {
    return {
      items: []
    }
  },
  created () {
    get('/posts')
        .then((rst) => { this.items = rst })
        .catch((err) => fail(this, err))
  }
}
</script>

// by-antd/src/plugins/site/posts/Index.jsx
import React, { Component } from 'react'
import {message} from 'antd'

import Layout from '../../../layouts/Application'
import {get} from '../../../ajax'
import Item from './Item'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/posts').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    return (
      <Layout breads={[{href: '/posts', label: 'site.posts.index.title'}]}>
        {this.state.items.map((p, i)=><Item key={i} value={p}/>)}
      </Layout>
    );
  }
}

export default Widget;
