// fly/src/plugins/site/admin/Info.vue
<template>
  <dashboard-layout title="site.admin.info.title" admin>
    <el-col :md="{span:16, offset:1}">
      <el-form ref="form" :model="form" :rules="rules" label-width="80px">
        <el-form-item :label="$t('site.attributes.title')" prop="title">
          <el-input v-model="form.title" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.subTitle')" prop="subTitle">
          <el-input v-model="form.subTitle" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.keywords')" prop="keywords">
          <el-input v-model="form.keywords" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.description')" prop="description">
          <el-input type="textarea" v-model="form.description" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.copyright')" prop="copyright">
          <el-input v-model="form.copyright" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        </el-form-item>
      </el-form>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get, post} from '@/ajax'

export default {
  data () {
    return {
      form: {
        title: '',
        subTitle: '',
        keywords: '',
        description: '',
        copyright: ''
      }
    }
  },
  created () {
    get('/site/info').then((rst) => { this.form = rst }).catch(this.$message.error)
  },
  computed: {
    rules () {
      return {
        title: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        subTitle: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        keywords: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        description: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        copyright: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/admin/site/info', this.form)
            .then(function (rst) {
              this.$message.success(this.$t('success'))
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    }
  }
}
</script>

// by-react/src/plugins/site/admin/Info.jsx
import React, {Component} from 'react'
import { Form, Input, message} from 'antd'
import i18n from 'i18next'

import Layout from '../../../layouts/Dashboard'
import {Submit, formItemLayout} from '../../../form'
import {post, get} from '../../../ajax'

const FormItem = Form.Item

class WidgetF extends Component {
  componentDidMount () {
    const {setFieldsValue} = this.props.form
    get('/site/info').then(
      function (rst){
        setFieldsValue({
          title: rst.title,
          subTitle: rst.subTitle,
          keywords: rst.keywords,
          description: rst.description,
          copyright: rst.copyright,
        })
      }
    )
  }

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        post('/admin/site/info', values).then((rst) => {
          message.success(i18n.t('success'));
        }).catch(message.error)
      }
    });
  }

  render() {
    const { getFieldDecorator } = this.props.form;

    return (
    <Layout  breadcrumb={[{label: 'site.admin.info.title', href: '/site/admin/info'}]}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.title')}
          hasFeedback
        >
          {getFieldDecorator('title', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.subTitle')}
          hasFeedback
        >
          {getFieldDecorator('subTitle', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.keywords')}
          hasFeedback
        >
          {getFieldDecorator('keywords', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.description')}
          hasFeedback
        >
          {getFieldDecorator('description', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input type="textarea" rows={6}/>
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.copyright')}
          hasFeedback
        >
          {getFieldDecorator('copyright', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <Submit />
      </Form>
    </Layout>
    );
  }
}

const Widget = Form.create()(WidgetF);

export default Widget
