// fly/src/components/Footer.vue
<template>
  <footer style="text-align:center">
    &copy; {{ $t("site.copyright") }}
    &middot; <a href="#">Privacy</a>
    &middot; <a href="#">Terms</a>
    {{$t('footer.other-languages')}}:
    <el-button type="text" key="l" v-on:click="setLocale(l)" v-for="l in languages">
      {{$t(`languages.${l}`)}}
    </el-button>
  </footer>
</template>

<script>
import {LANGUAGES, load as setLocale} from '@/i18n'

export default {
  data () {
    return {
      languages: LANGUAGES
    }
  },
  methods: {
    setLocale
  }
}
</script>

// by-react/src/components/Footer.jsx
import React from 'react'
import { Layout } from 'antd'
import i18n from 'i18next'

const { Footer } = Layout

const Widget = () => (
  <Footer style={{overflow: 'hidden', textAlign: 'center' }}>
    &copy;{i18n.t('site.copyright')}
    &middot; <a>nav 1</a>
    &middot; <a>nav 2</a> 
  </Footer>
)

export default Widget
