// desktop/src/plugins/auth/attachments/Edit.jsx
import React, { Component } from 'react'
import { Form, Input, message } from 'antd';
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'

import Layout from '../../../layouts/Dashboard'
import {formItemLayout} from '../../../constants'
import SubmitButton from '../../../components/SubmitButton'
import {post, get} from '../../../ajax'

const FormItem = Form.Item;

class WidgetF extends Component {
  componentDidMount () {
    const {setFieldsValue} = this.props.form
    const {match} = this.props
    get(`/attachments/${match.params.id}`).then(
      function (rst){
        setFieldsValue({title: rst.title})
      }
    ).catch(message.error)
  }
  handleSubmit = (e) => {
    e.preventDefault();
    const {formatMessage} = this.props.intl
    const {match, push} = this.props
    this.props.form.validateFieldsAndScroll((err, values) => {
     if (!err) {
       post(`/attachments/${match.params.id}`, values)
        .then((rst) => {
          message.success(formatMessage({id: 'messages.success'}))
          push('/attachments')
        }).catch(message.error)
     }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const { getFieldDecorator } = this.props.form;
    const {match} = this.props
    return (
      <Layout breads={[
          {href: '/attachments', label: 'auth.attachments.index.title'},
          {href: `/attachments/edit/${match.params.id}`, label: 'buttons.edit'},
        ]}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.title"/>}
            hasFeedback
          >
          {getFieldDecorator('title', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <SubmitButton />
        </Form>
      </Layout>
    );
  }
}


WidgetF.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired,
}

const Widget = Form.create()(injectIntl(WidgetF))

export default connect(
  state => ({}),
  {push},
)(Widget)

// dashboard/src/plugins/auth/attachments/Edit.vue
<template>
  <div>
    <group label-width="4.5em" label-margin-right="2em" label-align="right">
      <x-input
        required
        :title="$t('attributes.name')"
        :placeholder="$t('placeholders.not-empty')"
        v-model="form.title" />
    </group>
    <box gap="10px 10px">
      <x-button type="primary" @click.native="submitForm">{{$t("buttons.submit")}}</x-button>
    </box>
  </div>
</template>

<script>
import { Group, Box, XInput, XButton } from 'vux'
import { get, post, fail, success } from '@/ajax'

export default {
  components: {
    Group,
    XInput,
    XButton,
    Box
  },
  created () {
    get(`/attachments/${this.id}`).then((rst) => { this.form = rst }).catch((err) => fail(this, err))
  },
  data () {
    return {
      form: {
        title: ''
      }
    }
  },
  methods: {
    submitForm () {
      post(`/attachments/${this.id}`, this.form)
      .then(res => {
        success(this)
        this.$router.push({name: 'auth.attachments.index'})
      })
      .catch(err => fail(this, err))
    }
  },
  computed: {
    id () {
      return this.$route.params.id
    }
  }
}
</script>
