// fly/src/plugins/site/admin/Users.vue
<template>
  <dashboard-layout title="site.admin.users.index.title" admin>
    <el-col :md="{span: 22, offset: 1}">
      <el-table :data="items" border stripe style="width: 100%;">
        <el-table-column :label="$t('attributes.user')">
          <template scope="scope">
            {{scope.row.name}}&lt;{{scope.row.email}}&gt;[{{scope.row.signInCount}}]
          </template>
        </el-table-column>
        <el-table-column width="320" :label="$t('auth.attributes.user.currentSignIn')">
          <template scope="scope">
            {{scope.row.currentSignInAt}} [{{scope.row.currentSignInIp}}]
          </template>
        </el-table-column>
        <el-table-column width="320" :label="$t('auth.attributes.user.lastSignIn')">
          <template scope="scope">
            {{scope.row.lastSignInAt}} [{{scope.row.lastSignInIp}}]
          </template>
        </el-table-column>
      </el-table>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get} from '@/ajax'

export default {
  created () {
    get('/admin/users').then((rst) => { this.items = rst }).catch(this.$message.error)
  },
  data () {
    return {
      items: []
    }
  }
}
</script>

// desktop/src/plugins/site/admin/users/Index.jsx
import React, { Component } from 'react'
import { Table, Row, Col, message } from 'antd'
import {FormattedMessage} from 'react-intl'

import Layout from '../../../../layouts/Dashboard'
import {get} from '../../../../ajax'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/admin/users').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    const columns = [
      {
        title: <FormattedMessage id="site.admin.users.index.who"/>,
        key: 'who',
        render: (text, record) =>(<span>{record.name}&lt;{record.email}&gt;[{record.signInCount}]</span>)
      },
      {
        title: <FormattedMessage id="site.admin.users.index.lastSignIn"/>,
        key: 'lastSignIn',
        render: (text, record) =>(<span>{record.lastSignInAt}[{record.lastSignInIp}]</span>)
      },
      {
        title: <FormattedMessage id="site.admin.users.index.currentSignIn"/>,
        key: 'currentSignIn',
        render: (text, record) =>(<span>{record.currentSignInAt}[{record.currentSignInIp}]</span>)
      },
    ]

    return (
      <Layout admin breads={[{href: '/admin/users', label: 'site.admin.users.index.title'}]}>
        <Row>
          <Col>
            <Table bordered rowKey="id" columns={columns} dataSource={this.state.items} />
          </Col>
        </Row>
      </Layout>
    );
  }
}

export default Widget
