// dashboard/src/plugins/site/admin/Seo.jsx
import React, {Component} from 'react'
import { Form, Input, message, Card, Row, Col} from 'antd'
import i18n from 'i18next'

import Layout from '../../../layouts/Dashboard'
import {Submit, formItemLayout} from '../../../form'
import {post, get} from '../../../ajax'
import {LANGUAGES} from '../../../constants'

const FormItem = Form.Item

class WidgetF extends Component {
  state = {}
  componentDidMount () {
    const {setFieldsValue} = this.props.form
    get('/admin/site/seo').then(
      function (rst){
        setFieldsValue({
          googleVerifyCode: rst.googleVerifyCode,
          baiduVerifyCode: rst.baiduVerifyCode,
        })
        this.setState(rst)
      }.bind(this)
    )
  }

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        post('/admin/site/seo', values).then((rst) => {
          message.success(i18n.t('success'));
        }).catch(message.error)
      }
    });
  }

  render() {
    const { getFieldDecorator } = this.props.form;

    return (
    <Layout  breadcrumb={[{label: 'site.admin.seo.title', href: '/admin/site/seo'}]}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.admin.seo.googleVerifyCode')}
          hasFeedback
        >
          {getFieldDecorator('googleVerifyCode', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.admin.seo.baiduVerifyCode')}
          hasFeedback
        >
          {getFieldDecorator('baiduVerifyCode', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <Submit />
      </Form>
      <br/>
      <Row>
        <Col xs={{span: 24}} sm={{offset:4, span:16}}>
          <Card>
            {
              [
                `robots.txt`,
                `sitemap.xml.gz`,
                `google${this.state.googleVerifyCode}.html`,
                `baidu_verify_${this.state.baiduVerifyCode}.html`,
              ].concat(LANGUAGES.map((l)=>`rss-${l}.atom`)).map((n, i)=><p key={i}><a target="_blank" rel="noopener noreferrer" href={`/${n}`}>{n}</a></p>)
            }
          </Card>
        </Col>
      </Row>
    </Layout>
    );
  }
}

const Widget = Form.create()(WidgetF);

export default Widget

// mobile/src/plugins/site/admin/site/Seo.vue
<template>
  <dashboard-layout admin>
    <group label-width="6em" label-margin-right="2em" label-align="right">
      <x-input
        :title="$t('site.admin.seo.google.verifyCode')"
        v-model="form.googleVerifyCode" />
      <x-input
        :title="$t('site.admin.seo.baidu.verifyCode')"
        v-model="form.baiduVerifyCode" />
    </group>
    <box gap="10px 10px">
      <x-button type="primary" @click.native="submitForm">{{$t("buttons.submit")}}</x-button>
    </box>
    <group>
      <cell-box :key="i" v-for="(l, i) in links">
        <a :href="'/'+l" target="_blank">{{l}}</a>
      </cell-box>
    </group>
  </dashboard-layout>
</template>

<script>
import { Group, Box, CellBox, XInput, XTextarea, XButton } from 'vux'
import { mapState } from 'vuex'
import { get, post, fail, success } from '@/ajax'

export default {
  components: {
    Group,
    XInput,
    XButton,
    CellBox,
    Box,
    XTextarea
  },
  created () {
    get('/admin/site/seo').then((rst) => { this.form = rst }).catch((err) => fail(this, err))
  },
  data () {
    return {
      form: {
        googleVerifyCode: '',
        baiduVerifyCode: ''
      }
    }
  },
  methods: {
    submitForm () {
      post('/admin/site/seo', this.form)
      .then(res => success(this))
      .catch(err => fail(this, err))
    }
  },
  computed: {
    ...mapState({
      user: state => state.currentUser,
      info: state => state.siteInfo
    }),
    links () {
      return [
        'robots.txt',
        'sitemap.xml.gz',
        `google${this.form.googleVerifyCode}.html`,
        `baidu_verify_${this.form.baiduVerifyCode}.html`
      ].concat((this.info ? this.info.languages : []).map((l) => `rss-${l}.atom`))
    }
  }
}
</script>
