// fly/src/plugins/auth/users/ResetPassword.vue
<template>
  <non-sign-in-layout title="auth.users.reset-password.title">
    <el-form ref="form" :model="form" :rules="rules" label-width="80px">
      <el-form-item :label="$t('attributes.password')" prop="password">
        <el-input type="password" v-model="form.password" />
      </el-form-item>
      <el-form-item :label="$t('attributes.passwordConfirmation')" prop="passwordConfirmation">
        <el-input type="password" v-model="form.passwordConfirmation" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        <el-button @click="resetForm('form')">{{$t("buttons.reset")}}</el-button>
      </el-form-item>
    </el-form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  data () {
    return {
      form: {
        password: '',
        passwordConfirmation: ''
      }
    }
  },
  computed: {
    rules () {
      var password2 = (rule, value, callback) => {
        if (value !== this.form.password) {
          callback(new Error(this.$i18n.t('helpers.passwordConfirmation')))
        } else {
          callback()
        }
      }
      return {
        password: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' },
            { min: 6, max: 32, message: this.$t('helpers.password'), trigger: 'change' }
        ],
        passwordConfirmation: [
          { required: true, message: this.$i18n.t('helpers.not-empty'), trigger: 'change' },
          { validator: password2, trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          var data = Object.assign(this.form, {token: this.$route.params.token})
          post('/users/reset-password', data)
            .then(function (rst) {
              this.$message.success(this.$t('auth.messages.reset-password-success'))
              this.$router.push({name: 'auth.users.sign-in'})
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    },
    resetForm (formName) {
      this.$refs[formName].resetFields()
    }
  }
}
</script>

// by-react/src/plugins/auth/users/ResetPassword.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'

import { Form, Input, message} from 'antd'
import i18n from 'i18next'

import Layout from '../NonSignIn'
import {Submit, formItemLayout} from '../../../form'
import {post} from '../../../ajax'

const FormItem = Form.Item

class WidgetF extends Component {
  state = {
    confirmDirty: false
  };
  handleSubmit = (e) => {
    e.preventDefault();
    const {push, match} = this.props
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        post('/users/reset-password', Object.assign(values, {token: match.params.token})).then((rst) => {
          message.success(i18n.t('auth.messages.email-for-confirm'));
          push('/users/sign-in')
        }).catch(message.error)
      }
    });
  }
  handleConfirmBlur = (e) => {
    const value = e.target.value;
    this.setState({ confirmDirty: this.state.confirmDirty || !!value });
  }
  checkPassword = (rule, value, callback) => {
    const form = this.props.form;
    if (value && value !== form.getFieldValue('password')) {
      callback(i18n.t('helpers.passwordConfirmation'));
    } else {
      callback();
    }
  }
  checkPasswordConfirmation = (rule, value, callback) => {
    const form = this.props.form;
    if (value && this.state.confirmDirty) {
      form.validateFields(['passwordConfirmation'], { force: true });
    }
    callback();
  }

  render() {
    const { getFieldDecorator } = this.props.form;

    return (
    <Layout href="/users/reset-password" title="auth.users.reset-password.title">
      <Form onSubmit={this.handleSubmit}>
        <FormItem
          {...formItemLayout}
          label={i18n.t('attributes.password')}
          hasFeedback
        >
          {getFieldDecorator('password', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }, {
              validator: this.checkPasswordConfirmation,
            }],
          })(
            <Input type="password" />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('attributes.passwordConfirmation')}
          hasFeedback
        >
          {getFieldDecorator('passwordConfirmation', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }, {
              validator: this.checkPassword,
            }],
          })(
            <Input type="password" onBlur={this.handleConfirmBlur} />
          )}
        </FormItem>
        <Submit />
      </Form>
    </Layout>
    );
  }
}

WidgetF.propTypes = {
  push: PropTypes.func.isRequired
}

const Widget = Form.create()(WidgetF);


// class Widget extends Component{
//   state = { password: '', passwordConfirmation: '' }
//
//   handleChange = (e, { name, value }) => this.setState({ [name]: value })
//
//   handleSubmit = e => {
//     e.preventDefault()
//     const {push, match} = this.props
//     var data = new URLSearchParams()
//     data.append('token', match.params.token)
//     data.append('password', this.state.password)
//     data.append('passwordConfirmation', this.state.passwordConfirmation)
//     post('/users/reset-password', data).then((rst) => {
//       alert(rst.message)
//       push('/users/sign-in')
//     }).catch(alert)
//   }
//   render() {
//     const {password, passwordConfirmation} = this.state;
//     return (
//       <Layout title="auth.users.reset-password.title">
//         <Form onSubmit={this.handleSubmit}>
//           <Form.Input name='password' value={password} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.password"/>} />
//           <Form.Input name='passwordConfirmation' value={passwordConfirmation} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.passwordConfirmation"/>} />
//           <Submit />
//         </Form>
//       </Layout>
//     )
//   }
// }

export default connect(
  state => ({}),
  {push},
)(Widget)
