// dashboard/src/plugins/site/leave-words/New.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'
import { Form, Input, message} from 'antd'
import i18n from 'i18next'

import Layout from '../../auth/NonSignIn'
import {Submit, formItemLayout} from '../../../form'
import {post} from '../../../ajax'

const FormItem = Form.Item

class WidgetF extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    const {setFieldsValue, validateFields} = this.props.form
    validateFields((err, values) => {
      if (!err) {
        post('/leave-words', Object.assign(values, {type: 'text'})).then((rst) => {
          message.success(i18n.t('success'))
          setFieldsValue({body: ''})
        }).catch(message.error)
      }
    });
  }
  render() {
    const { getFieldDecorator } = this.props.form;
    return (
      <Layout title="site.leave-words.new.title">
        <Form onSubmit={this.handleSubmit}>
          <FormItem
            {...formItemLayout}
            label={i18n.t('attributes.content')}
            extra={i18n.t('site.helpers.leave-word.body')}
            hasFeedback
          >
            {getFieldDecorator('body', {
              rules: [{
                required: true, message: i18n.t('helpers.not-empty'),
              }],
            })(
              <Input type="textarea" rows={6} />
            )}
          </FormItem>
          <Submit />
        </Form>
      </Layout>
    );
  }
}

WidgetF.propTypes = {
  push: PropTypes.func.isRequired
}

const Widget = Form.create()(WidgetF);

export default connect(
  state => ({}),
  {push},
)(Widget)

// fly/src/plugins/site/leave-words/New.vue
<template>
  <non-sign-in-layout title="site.leave-words.new.title">
    <el-form ref="form" :model="form" :rules="rules" label-width="80px">
      <el-form-item :label="$t('attributes.content')" prop="body">
        <el-input type="textarea" v-model="form.body" />
        <span>{{$t('site.helpers.leave-word.body')}}</span>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        <el-button @click="resetForm('form')">{{$t("buttons.reset")}}</el-button>
      </el-form-item>
    </el-form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  props: ['action'],
  data () {
    return {
      form: {
        body: ''
      }
    }
  },
  computed: {
    rules () {
      return {
        body: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/leave-words', Object.assign(this.form, {type: 'text'}))
            .then(function (rst) {
              this.$message.success(this.$t('success'))
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    },
    resetForm (formName) {
      this.$refs[formName].resetFields()
    }
  }
}
</script>
