// by-react/src/plugins/auth/users/SignIn.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'
import { Form, Input, message} from 'antd'
import i18n from 'i18next'

import Layout from '../NonSignIn'
import {Submit, formItemLayout} from '../../../form'
import {post} from '../../../ajax'
import {signIn} from '../../../actions'
import {TOKEN} from '../../../constants'

const FormItem = Form.Item

class WidgetF extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        const {push, signIn} = this.props
        post('/users/sign-in', values).then((rst) => {
          message.success(i18n.t('success'))
          sessionStorage.setItem(TOKEN, rst.token)
          signIn(rst.token)
          push('/dashboard')
        }).catch(message.error)
      }
    });
  }
  render() {
    const { getFieldDecorator } = this.props.form;
    return (
      <Layout href="/users/sign-in" title="auth.users.sign-in.title">
        <Form onSubmit={this.handleSubmit}>
          <FormItem
            {...formItemLayout}
            label={i18n.t('attributes.email')}
            hasFeedback
          >
            {getFieldDecorator('email', {
              rules: [{
                type: 'email', message: i18n.t('helpers.bad-email'),
              }, {
                required: true, message: i18n.t('helpers.not-empty'),
              }],
            })(
              <Input />
            )}
          </FormItem>
          <FormItem
            {...formItemLayout}
            label={i18n.t('attributes.password')}
            hasFeedback
          >
            {getFieldDecorator('password', {
              rules: [{
                required: true, message: i18n.t('helpers.not-empty'),
              }],
            })(
              <Input type="password" />
            )}
          </FormItem>
          <Submit />
        </Form>
      </Layout>
    );
  }
}

WidgetF.propTypes = {
  push: PropTypes.func.isRequired,
  signIn: PropTypes.func.isRequired
}

const Widget = Form.create()(WidgetF);

export default connect(
  state => ({}),
  {push, signIn},
)(Widget)

// by-vue/src/plugins/auth/users/SignIn.vue
<template>
  <non-sign-in-layout title="auth.users.sign-in.title">
    <el-form ref="form" :model="form" :rules="rules" label-width="80px">
      <el-form-item :label="$t('attributes.email')" prop="email">
        <el-input v-model="form.email" />
      </el-form-item>
      <el-form-item :label="$t('attributes.password')" prop="password">
        <el-input type="password" v-model="form.password" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        <el-button @click="resetForm('form')">{{$t("buttons.reset")}}</el-button>
      </el-form-item>
    </el-form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'
import {TOKEN} from '@/constants'

export default {
  data () {
    return {
      form: {
        email: '',
        password: ''
      }
    }
  },
  computed: {
    rules () {
      return {
        email: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' },
          { type: 'email', message: this.$t('helpers.bad-email'), trigger: 'change' }
        ],
        password: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/users/sign-in', this.form)
            .then(function (rst) {
              var token = rst.token
              sessionStorage.setItem(TOKEN, token)
              this.$store.commit('signIn', token)
              this.$router.push({name: 'site.dashboard'})
              this.$message.success(this.$t('success'))
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    },
    resetForm (formName) {
      this.$refs[formName].resetFields()
    }
  }
}
</script>
