// by-react/src/plugins/auth/Attachments.jsx
import React, {Component} from 'react'
import { Upload, Button, Icon, Row, Col, message } from 'antd'
import i18n from 'i18next'

import Layout from '../../layouts/Dashboard'
import {get, api, _delete} from '../../ajax'
import {TOKEN} from '../../constants'


class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/attachments').then(
      function (rst){
        this.setState({
          items: rst.map((a)=>{
            return {uid:a.id,name:a.title,status:'done',url:a.url}
          })
        })
      }.bind(this)
    )
  }
  handleRemove = (info) => {
    if(window.confirm(i18n.t('are-you-sure'))){
      _delete(`/attachments/${info.uid}`)
        .then((rst)=>{
          message.success(i18n.t('success'))
        })
        .catch(message.error)
      return true
    }
    return false
  }
  handleChange = (info) => {
    let fileList = info.fileList;

    // 1. Limit the number of uploaded files
    //    Only to show two recent uploaded files, and old ones will be replaced by the new
    // fileList = fileList.slice(-2);

    // 2. read from response and show file link
    fileList = fileList.map((file) => {
      if (file.response) {
        // Component will show file.url as link
        file.url = file.response.url;
        file.uid = file.response.uid;
      }
      return file;
    });

    // 3. filter successfully uploaded files according to response from server
    fileList = fileList.filter((file) => {
      if (file.response) {
        return file.response.status === 'success';
      }
      return true;
    });

    this.setState({ items: fileList });
  }
  render() {
    const props = {
      action: api('/antd/attachments'),
      onChange: this.handleChange,
      onRemove: this.handleRemove,
      multiple: true,
      withCredentials: true,
      headers: {
        // https://github.com/react-component/upload/issues/33
        'X-Requested-With': null,
        'Authorization': `BEARER ${window.sessionStorage.getItem(TOKEN)}`
      },
    };

    return (
      <Layout breadcrumb={[{label: 'auth.attachments.index.title', href: '/attachments'}]}>
        <Row>
          <Col span={8} offset={2}>
            <Upload {...props} fileList={this.state.items}>
              <Button>
                <Icon type="upload" /> {i18n.t('buttons.upload')}
              </Button>
            </Upload>
          </Col>
        </Row>
      </Layout>
    );
  }
}

export default Widget

// dashboard/src/plugins/auth/Attachments.vue
<template>
  <dashboard-layout title="auth.attachments.index.title">
    <el-col :md="{span: 22, offset: 1}">
      <el-upload :file-list="fileList"
        :on-preview="handlePreview"
        :on-success="handleSuccess"
        :headers="headers"
        multiple
        :action="action">
        <el-button size="small" type="primary">
          {{$t("buttons.upload")}}
          <i class="el-icon-upload el-icon--right"/>
        </el-button>
        <div slot="tip"></div>
      </el-upload>
      <br/>
      <el-table :data="items" border stripe style="width: 100%">
        <el-table-column  :label="$t('attributes.name')">
          <template scope="scope">
            <a target="_blank" :href="scope.row.url">{{scope.row.title}}</a>
          </template>
        </el-table-column>
        <el-table-column width="100" :label="$t('attributes.size')">
          <template scope="scope">
            <span>{{ scope.row.length }}KB</span>
          </template>
        </el-table-column>
        <el-table-column width="240" :label="$t('buttons.manage')">
          <template scope="scope">
            <el-button-group>
              <el-button @click="handleCopy(scope.row.url)" type="info" size="mini" icon="share" />
              <el-button @click="handleRemove(scope.row.id)" type="danger" size="mini" icon="delete" />
            </el-button-group>
          </template>
        </el-table-column>
      </el-table>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get, _delete, api} from '@/ajax'
import {TOKEN} from '@/constants'

export default {
  created () {
    get('/attachments').then((rst) => { this.items = rst }).catch(this.$message.error)
  },
  data () {
    return {
      items: [],
      fileList: [],
      headers: {
        // https://github.com/react-component/upload/issues/33
        'X-Requested-With': null,
        'Authorization': `BEARER ${window.sessionStorage.getItem(TOKEN)}`
      }
    }
  },
  computed: {
    action () {
      return api('/antd/attachments')
    }
  },
  methods: {
    handlePreview (info) {
      window.open(info.response.url, '_blank')
    },
    handleSuccess (response, file, fileList) {
      this.items.unshift({id: response.uid, title: response.url, url: response.url})
    },
    handleCopy (url) {
      this.$alert(url, 'URL', {
        confirmButtonText: this.$t('buttons.ok'),
        callback: action => {}
      })
    },
    handleRemove (id) {
      this.$confirm(
        this.$t('are-you-sure'),
        '',
        {
          confirmButtonText: this.$t('buttons.ok'),
          cancelButtonText: this.$t('buttons.cancel'),
          type: 'warning'
        }
      )
      .then(() => {
        _delete(`/attachments/${id}`).then(function (rst) {
          this.$message.success('success')
          this.items = this.items.filter((a) => a.id !== id)
        }.bind(this)).catch(this.$message.error)
      })
      .catch(() => {})
    }
  }
}
</script>
