// fly/src/layouts/NonSignIn.vue
<template>
  <application-layout>
    <el-col :md="{span: 12, offset:6}">
      <h2>{{$t(title)}}</h2>
      <slot />
      <ul class="list-group">
        <li v-for="l in links" key="l">
          <fa-icon :name="l.icon" />
          <router-link :to="{name: l.href}">
            {{$t(`${l.href}.title`)}}
          </router-link>
        </li>
      </ul>
    </el-col>
  </application-layout>
</template>

<script>
import {nonSignInLinks as links} from '@/constants'

export default {
  props: ['title'],
  data () {
    return {
      links
    }
  }
}
</script>

// dashboard/src/plugins/auth/NonSignIn.jsx
import React from 'react'
import PropTypes from 'prop-types'
import {FormattedMessage} from 'react-intl'
import {Link} from 'react-router-dom'
import { Row, Col, Icon } from 'antd'

import Layout from '../../layouts/Application'
import {NonSignInLinks} from '../../constants'

const Widget = ({title, children}) => (
  <Layout>
    <Row>
      <Col span={12} offset={6}>
        <h3 style={{margin: '16px 0'}}><FormattedMessage id={title}/></h3>

        {children}

        <ul style={{margin: '16px 0'}}>
          {
            NonSignInLinks.map((l, i) => <li key={i}><Icon type={l.icon} /><Link style={{margin: '6px'}} to={l.href}><FormattedMessage id={l.label} /></Link></li>)
          }
        </ul>
      </Col>
    </Row>
  </Layout>
)

Widget.propTypes = {
  title: PropTypes.string.isRequired,
  children: PropTypes.node.isRequired
}

export default Widget
