// by-antd/src/plugins/forms/Edit.jsx
import React, { Component } from 'react'
import { Form, Input, Select, Row, Col, DatePicker, Icon, Button, message } from 'antd';
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'
import moment from 'moment';
import uuid from 'uuid/v4'

import Layout from '../../layouts/Dashboard'
import {formItemLayout, tailFormItemLayout, DATE_FORMAT} from '../../constants'
import {post, get} from '../../ajax'

const FormItem = Form.Item;
const Option = Select.Option;

class WidgetF extends Component {
  componentDidMount () {
    const {setFieldsValue,getFieldDecorator} = this.props.form
    const {id} = this.props.match.params
    if (id) {
      get(`/forms/${id}`).then((rst)=>{
        var data = {
          title: rst.title,
          body: rst.body,
          deadline: moment(rst.deadline, DATE_FORMAT),
          fields: [],
        }
        rst.fields.forEach((f) => {
          const id = uuid()
          data.fields.push(id)

          getFieldDecorator(`names-${id}`, { initialValue: '' });
          data[`names-${id}`] = f.name
          getFieldDecorator(`labels-${id}`, { initialValue: '' });
          data[`labels-${id}`] = f.label
          getFieldDecorator(`types-${id}`, { initialValue: '' });
          data[`types-${id}`] = f.type
          getFieldDecorator(`values-${id}`, { initialValue: '' });
          data[`values-${id}`] = f.value
          getFieldDecorator(`bodys-${id}`, { initialValue: '' });
          data[`bodys-${id}`] = f.body
        })

        setFieldsValue(data)
      }).catch(message.error)
    }else{
      setFieldsValue({
        deadline: moment(new Date(), DATE_FORMAT),
      })
    }
  }
  onAppend = (e) => {
    const { form } = this.props;
    const fields = form.getFieldValue('fields');
    fields.push(uuid())
    form.setFieldsValue({fields});
  }
  onRemove = (id) => {
    const { form } = this.props;
    const fields = form.getFieldValue('fields');
    form.setFieldsValue({
      fields: fields.filter((f)=>f !== id),
    });
  }
  handleSubmit = (e) => {
    e.preventDefault();
    const {formatMessage} = this.props.intl
    const {push, match} = this.props
    const {id} = match.params

    this.props.form.validateFieldsAndScroll((err, values) => {
     if (!err) {
      //  console.log(values)
       var data = {
         title: values.title,
         body: values.body,
         type: 'markdown',
         deadline: values.deadline,
         fields: values.fields.map((id) => ({
           label: values[`labels-${id}`],
           name: values[`names-${id}`],
           type: values[`types-${id}`],
           value: values[`values-${id}`],
           body: values[`bodys-${id}`],
         }))
       }
      //  console.log(data)
       post(id ? `/forms/${id}` : '/forms', data)
        .then((rst) => {
          message.success(formatMessage({id: 'messages.success'}))
          push('/forms/manage')
        }).catch(message.error)
     }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const { getFieldDecorator, getFieldValue } = this.props.form;
    const {id} = this.props.match.params

    getFieldDecorator('fields', { initialValue: [] });


    const fields = getFieldValue('fields').map((f, i) => {
      return (
        <div key={i}>
          <Row>
            <Col sm={{offset:5}}>
              <h2>
                <FormattedMessage id="forms.edit.field_item" values={{id:i+1}}/>
                <Icon
                  className="dynamic-delete-button"
                  type="minus-circle-o"
                  onClick={() => this.onRemove(f)}
                />
            </h2>
            </Col>
          </Row>
          <FormItem
           {...formItemLayout}
           label={<FormattedMessage id="attributes.name"/>}
           hasFeedback
         >
         {getFieldDecorator(`names-${f}`, {
           rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
         })(
           <Input />
         )}
         </FormItem>
         <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.type"/>}
            hasFeedback
          >
          {getFieldDecorator(`types-${f}`, {
            rules:[{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Select style={{ width: 120 }}>
              {['text', 'checkboxs', 'radios', 'select', 'textarea'].map((t, i)=><Option key={i} value={t}>{t}</Option>)}
            </Select>
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.value"/>}
            hasFeedback
          >
          {getFieldDecorator(`values-${f}`, {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.label"/>}
            hasFeedback
          >
          {getFieldDecorator(`labels-${f}`, {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.body"/>}
            hasFeedback
          >
          {getFieldDecorator(`bodys-${f}`, {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input type="textarea" rows="10" />
          )}
          </FormItem>


        </div>
      );
    });

    return (
      <Layout breads={[
          {href: '/forms/manage', label: 'forms.manage.title'},
          {href: id ? `/forms/edit/${id}` : '/forms/new', label: id ? 'buttons.edit': 'buttons.new'},
        ]}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.title"/>}
            hasFeedback
          >
          {getFieldDecorator('title', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.body"/>}
            hasFeedback
          >
          {getFieldDecorator('body', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input type="textarea" rows="10" />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.deadline"/>}
            hasFeedback
          >
          {getFieldDecorator('deadline', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <DatePicker />
          )}
          </FormItem>

          {fields}

          <FormItem {...tailFormItemLayout}>
            <Button onClick={this.onAppend}><FormattedMessage id="forms.edit.add_field"/></Button>
            &nbsp; &nbsp;
            <Button type="primary" htmlType="submit" size="large">
              <FormattedMessage id="buttons.submit"/>
            </Button>
          </FormItem>

        </Form>
      </Layout>
    );
  }
}


WidgetF.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired,
}

const Widget = Form.create()(injectIntl(WidgetF))

export default connect(
  state => ({}),
  {push},
)(Widget)

// dashboard/src/plugins/forms/Edit.vue
<template>
  <dashboard-layout :title="id ? 'buttons.edit' : 'buttons.new'" admin>
    <el-col :md="{span: 16, offset: 4}">
      <el-form ref="form" :model="form" :rules="rules" label-width="80px">
        <el-form-item :label="$t('attributes.title')" prop="title">
          <el-input v-model="form.title" />
        </el-form-item>
        <el-form-item :label="$t('attributes.body')" prop="body">
          <el-input type="textarea" v-model="form.body" />
          <span>{{$t('helpers.markdown')}}</span>
        </el-form-item>
        <el-form-item :label="$t('attributes.shutDown')" prop="deadline">
          <el-date-picker
            v-model="form.deadline"
            type="date"
            :picker-options="pickerOptions">
          </el-date-picker>
        </el-form-item>
        <div :key="i" v-for="(f, i) in form.fields">
          <h4>{{$t('forms.attributes.form.fields')}} {{i}}</h4>
          <el-form-item :label="$t('attributes.type')" :prop="'fields.' + i + '.type'">
            <el-select v-model="f.type">
              <el-option :key="v" :label="v" :value="v" v-for="v in ['text', 'email', 'checkboxs', 'radios']" />
            </el-select>
          </el-form-item>
          <el-form-item
              :label="$t('attributes.name')"
              :prop="'fields.' + i + '.name'"
              :rules="not_empty"
              >
              <el-input v-model="f.name" />
          </el-form-item>
          <el-form-item
              :label="$t('attributes.default')"
              :prop="'fields.' + i + '.value'"
              >
              <el-input v-model="f.value" />
          </el-form-item>
          <el-form-item
              :label="$t('attributes.label')"
              :prop="'fields.' + i + '.label'"
              :rules="not_empty"
              >
              <el-input v-model="f.label" />
          </el-form-item>
          <el-form-item
              :label="$t('attributes.content')"
              :prop="'fields.' + i + '.body'"
              >
              <el-input type="textarea" v-model="f.body" />
              <span>{{$t('helpers.one-record-per-line')}}</span>
          </el-form-item>
          <el-form-item>
            <el-button size="small" @click.prevent="removeField(f)">{{$t('buttons.remove')}}</el-button>
          </el-form-item>
        </div>
        <el-form-item>
          <el-button @click="addField">{{$t('forms.index.add-field')}}</el-button>
          <el-button type="primary" @click="handleSubmit('form')">{{$t("buttons.submit")}}</el-button>
        </el-form-item>
      </el-form>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get, post} from '@/ajax'

export default {
  data () {
    return {
      pickerOptions: {
        disabledDate (time) {
          return time.getTime() < Date.now() - 8.64e7
        }
      },
      form: {
        title: '',
        body: '',
        deadline: '',
        fields: []
      },
      title: ''
    }
  },
  computed: {
    id () {
      return this.$route.params.id
    },
    not_empty () {
      return {
        required: true, message: this.$t('helpers.not-empty')
      }
    },
    rules () {
      return {
        title: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        body: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        deadline: [
          { type: 'date', required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ]
      }
    }
  },
  created () {
    if (this.id) {
      get(`/forms/models/${this.id}`).then((rst) => {
        this.form = Object.assign({}, rst, {deadline: new Date(rst.deadline)})
      }).catch(this.$message.error)
    }
  },
  methods: {
    addField () {
      this.form.fields.push({name: '', type: 'text', body: '', label: ''})
    },
    removeField (item) {
      var idx = this.form.fields.indexOf(item)
      if (idx !== -1) {
        this.form.fields.splice(idx, 1)
      }
    },
    handleSubmit (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post(this.id ? `/forms/models/${this.id}` : '/forms/models', Object.assign({}, this.form, {type: 'markdown'}))
            .then(function (rst) {
              this.$message.success(this.$t('success'))
              this.$router.push({name: 'forms.index'})
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    }
  }
}
</script>
