// by-antd/src/plugins/site/posts/Index.jsx
import React, { Component } from 'react'
import {message} from 'antd'

import Layout from '../../../layouts/Application'
import {get} from '../../../ajax'
import Item from './Item'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/posts').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    return (
      <Layout breads={[{href: '/posts', label: 'site.posts.index.title'}]}>
        {this.state.items.map((p, i)=><Item key={i} value={p}/>)}
      </Layout>
    );
  }
}

export default Widget;

// by-vue/src/plugins/site/posts/Index.vue
<template>
  <application-layout>
    <el-col :md="{span:16, offset:4}" :key={i} v-for="(o, i) in items">
      <router-link target="_blank" :to="{name: 'posts.show', params: {name: o.name}}"><h2>{{o.title}}</h2></router-link>
      <md2ht :body="o.body" />
    </el-col>
  </application-layout>
</template>

<script>
import {get} from '@/ajax'

export default {
  data () {
    return {
      items: []
    }
  },
  created () {
    get('/posts').then((rst) => { this.items = rst }).catch(this.$message.error)
  }
}
</script>
