// dashboard/src/plugins/site/admin/Seo.jsx
import React, {Component} from 'react'
import { Form, Input, message, Card, Row, Col} from 'antd'
import i18n from 'i18next'

import Layout from '../../../layouts/Dashboard'
import {Submit, formItemLayout} from '../../../form'
import {post, get} from '../../../ajax'
import {LANGUAGES} from '../../../constants'

const FormItem = Form.Item

class WidgetF extends Component {
  state = {}
  componentDidMount () {
    const {setFieldsValue} = this.props.form
    get('/admin/site/seo').then(
      function (rst){
        setFieldsValue({
          googleVerifyCode: rst.googleVerifyCode,
          baiduVerifyCode: rst.baiduVerifyCode,
        })
        this.setState(rst)
      }.bind(this)
    )
  }

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        post('/admin/site/seo', values).then((rst) => {
          message.success(i18n.t('success'));
        }).catch(message.error)
      }
    });
  }

  render() {
    const { getFieldDecorator } = this.props.form;

    return (
    <Layout  breadcrumb={[{label: 'site.admin.seo.title', href: '/admin/site/seo'}]}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.admin.seo.googleVerifyCode')}
          hasFeedback
        >
          {getFieldDecorator('googleVerifyCode', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.admin.seo.baiduVerifyCode')}
          hasFeedback
        >
          {getFieldDecorator('baiduVerifyCode', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <Submit />
      </Form>
      <br/>
      <Row>
        <Col xs={{span: 24}} sm={{offset:4, span:16}}>
          <Card>
            {
              [
                `robots.txt`,
                `sitemap.xml.gz`,
                `google${this.state.googleVerifyCode}.html`,
                `baidu_verify_${this.state.baiduVerifyCode}.html`,
              ].concat(LANGUAGES.map((l)=>`rss-${l}.atom`)).map((n, i)=><p key={i}><a target="_blank" rel="noopener noreferrer" href={`/${n}`}>{n}</a></p>)
            }
          </Card>
        </Col>
      </Row>
    </Layout>
    );
  }
}

const Widget = Form.create()(WidgetF);

export default Widget

// fly/src/plugins/site/admin/Seo.vue
<template>
  <dashboard-layout title="site.admin.seo.title">
    <el-col :md="{span:16, offset:1}">
      <el-form ref="form" :model="form" :rules="rules" label-width="120px">
        <el-form-item :label="$t('site.admin.seo.googleVerifyCode')" prop="googleVerifyCode">
          <el-input v-model="form.googleVerifyCode" />
        </el-form-item>
        <el-form-item :label="$t('site.admin.seo.baiduVerifyCode')" prop="baiduVerifyCode">
          <el-input v-model="form.baiduVerifyCode" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        </el-form-item>
      </el-form>
    </el-col>
    <el-col :md="{span:16, offset:3}">
      <ul class="list-group">
        <li :key="i" v-for="(l, i) in links">
          <a :href="`/${l}`" target="_blank">{{l}}</a>
        </li>
      </ul>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get, post} from '@/ajax'
import {LANGUAGES} from '@/i18n'

export default {
  data () {
    return {
      form: {
        googleVerifyCode: '',
        baiduVerifyCode: ''
      }
    }
  },
  created () {
    get('/admin/site/seo').then((rst) => { this.form = rst }).catch(this.$message.error)
  },
  computed: {
    rules () {
      return {
      }
    },
    links () {
      return [
        'robots.txt',
        'sitemap.xml.gz',
        `google${this.form.googleVerifyCode}.html`,
        `baidu_verify_${this.form.baiduVerifyCode}.html`
      ].concat(LANGUAGES.map((l) => `rss-${l}.atom`))
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/admin/site/seo', this.form)
            .then(function (rst) {
              this.$message.success(this.$t('success'))
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    }
  }
}
</script>
