// fly/src/plugins/site/notices/Index.vue
<template>
  <application-layout>
    <el-col :md="{span:16, offset:4}">
      <h2 style="padding-left: 20px;">{{$t('site.notices.index.title')}}</h2>
    </el-col>
    <el-col :md="{span:16, offset:4}" :key={i} v-for="(n, i) in items">
      <blockquote>
        <md2ht :body="n.body" />
        <footer>--<cite title="Source Title">{{n.updatedAt}}</cite></footer>
      </blockquote>
    </el-col>
  </application-layout>
</template>

<script>
import {get} from '@/ajax'

export default {
  data () {
    return {
      items: []
    }
  },
  created () {
    get('/notices').then((rst) => { this.items = rst }).catch(this.$message.error)
  }
}
</script>

// by-antd/src/plugins/site/notices/Index.jsx
import React, { Component } from 'react'
import {message, Card} from 'antd'
import TimeAgo from 'timeago-react'
import Markdown from 'react-markdown'

import Layout from '../../../layouts/Application'
import {get} from '../../../ajax'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/notices').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    return (
      <Layout breads={[{href: '/posts', label: 'site.posts.index.title'}]}>
        {this.state.items.map((n, i)=><Card title={<TimeAgo datetime={n.updatedAt}/>} style={{margin: '16px'}} key={i}><Markdown source={n.body} /></Card>)}
      </Layout>
    );
  }
}

export default Widget;
