// desktop/src/plugins/site/notices/Index.vue
<template>
  <group
    :title="$t('site.posts.index.title')"
  >
    <cell
      :key="i"
      :title="l.body.substring(0, 20)"
      :link="{name: 'site.notices.show', params: {id: l.id}}"
      v-for="(l, i) in items">
      <time-ago :date="l.updatedAt"/>
    </cell>
  </group>
</template>

<script>
import { Group, Cell } from 'vux'
import { get, fail } from '@/ajax'

export default {
  components: {
    Group,
    Cell
  },
  data () {
    return {
      items: []
    }
  },
  created () {
    get('/notices')
        .then((rst) => { this.items = rst })
        .catch((err) => fail(this, err))
  }
}
</script>

// by-antd/src/plugins/site/notices/Index.jsx
import React, { Component } from 'react'
import {message, Card} from 'antd'
import TimeAgo from 'timeago-react'
import Markdown from 'react-markdown'

import Layout from '../../../layouts/Application'
import {get} from '../../../ajax'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/notices').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    return (
      <Layout breads={[{href: '/posts', label: 'site.posts.index.title'}]}>
        {this.state.items.map((n, i)=><Card title={<TimeAgo datetime={n.updatedAt}/>} style={{margin: '16px'}} key={i}><Markdown source={n.body} /></Card>)}
      </Layout>
    );
  }
}

export default Widget;
