// desktop/src/plugins/site/admin/users/Index.jsx
import React, { Component } from 'react'
import { Table, Row, Col, message } from 'antd'
import {FormattedMessage} from 'react-intl'

import Layout from '../../../../layouts/Dashboard'
import {get} from '../../../../ajax'

class Widget extends Component {
  state = { items: []}
  componentDidMount () {
    get('/admin/users').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  render() {
    const columns = [
      {
        title: <FormattedMessage id="site.admin.users.index.who"/>,
        key: 'who',
        render: (text, record) =>(<span>{record.name}&lt;{record.email}&gt;[{record.signInCount}]</span>)
      },
      {
        title: <FormattedMessage id="site.admin.users.index.lastSignIn"/>,
        key: 'lastSignIn',
        render: (text, record) =>(<span>{record.lastSignInAt}[{record.lastSignInIp}]</span>)
      },
      {
        title: <FormattedMessage id="site.admin.users.index.currentSignIn"/>,
        key: 'currentSignIn',
        render: (text, record) =>(<span>{record.currentSignInAt}[{record.currentSignInIp}]</span>)
      },
    ]

    return (
      <Layout admin breads={[{href: '/admin/users', label: 'site.admin.users.index.title'}]}>
        <Row>
          <Col>
            <Table bordered rowKey="id" columns={columns} dataSource={this.state.items} />
          </Col>
        </Row>
      </Layout>
    );
  }
}

export default Widget

// by-iview/src/plugins/site/admin/users/Index.vue
<template>
  <dashboard-layout admin>
    <x-table full-bordered>
      <thead>
        <tr>
          <th>{{$t('site.admin.users.index.who')}}</th>
          <th>{{$t('site.admin.users.index.lastSignIn')}}</th>
          <th>{{$t('site.admin.users.index.currentSignIn')}}</th>
        </tr>
      </thead>
      <tbody>
        <tr :key="i" v-for="(l, i) in items">
          <td>{{l.name}}&lt;{{l.email}}&gt;[{{l.signInCount}}]</td>
          <td>{{l.lastSignInAt}}[{{l.lastSignInIp}}]</td>
          <td>{{l.currentSignInAt}}[{{l.currentSignInIp}}]</td>
        </tr>
      </tbody>
    </x-table>
  </dashboard-layout>
</template>

<script>
import { XTable } from 'vux'
import {get, fail} from '@/ajax'

export default {
  components: {
    XTable
  },
  created () {
    get('/admin/users').then((rst) => { this.items = rst }).catch((err) => fail(this, err))
  },
  data () {
    return {
      items: []
    }
  }
}
</script>
