// desktop/src/plugins/site/Install.jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types'
import { Form, Input, message } from 'antd';
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import { connect } from 'react-redux'
import { push } from 'react-router-redux'

import Layout from '../../layouts/NonSignIn'
import {formItemLayout} from '../../constants'
import SubmitButton from '../../components/SubmitButton'
import {post} from '../../ajax'

const FormItem = Form.Item;

class WidgetF extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    const {formatMessage} = this.props.intl
    const {push} = this.props
    this.props.form.validateFieldsAndScroll((err, values) => {
     if (!err) {
       post('/install', values)
        .then((rst) => {
          message.success(formatMessage({id: 'messages.success'}))
          push('/users/sign-in')
        }).catch(message.error)
     }
    });
  }
  checkPasswords = (rule, value, callback) => {
    const {formatMessage} = this.props.intl
    const form = this.props.form;
    if (value && value !== form.getFieldValue('password')) {
      callback(formatMessage({id: "errors.passwordConfirmation"}));
    } else {
      callback();
    }
  }
  render() {
    const {formatMessage} = this.props.intl
    const { getFieldDecorator } = this.props.form;
    return (
      <Layout title="site.install.title">
        <Form onSubmit={this.handleSubmit}>
          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="site.attributes.title"/>}
            hasFeedback
          >
          {getFieldDecorator('title', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="site.attributes.subTitle"/>}
            hasFeedback
          >
          {getFieldDecorator('subTitle', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.username"/>}
            hasFeedback
          >
          {getFieldDecorator('name', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.email"/>}
            hasFeedback
          >
          {getFieldDecorator('email', {
            rules: [
              { required: true, message: formatMessage({id:"errors.not-empty"})},
              { type: 'email', message: formatMessage({id:"errors.not-valid-email"})},
            ],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.password"/>}
            hasFeedback
          >
          {getFieldDecorator('password', {
            rules: [
              { required: true, min: 6, max: 32, message: formatMessage({id:"errors.password"})},
            ],
          })(
            <Input type="password" />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="attributes.passwordConfirmation"/>}
            hasFeedback
          >
          {getFieldDecorator('passwordConfirmation', {
            rules: [
              { required: true, message: formatMessage({id:"errors.not-empty"})},
              {validator: this.checkPasswords},
            ],
          })(
            <Input type="password" />
          )}
          </FormItem>
          <SubmitButton />
        </Form>
      </Layout>
    );
  }
}

WidgetF.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired,
}

const Widget = Form.create()(injectIntl(WidgetF))

export default connect(
  state => ({}),
  {push},
)(Widget)

// by-vue/src/plugins/site/Install.vue
<template>
  <non-sign-in-layout title="site.install.title">
    <el-form ref="form" :model="form" :rules="rules" label-width="80px">
      <el-form-item :label="$t('site.attributes.title')" prop="title">
        <el-input v-model="form.title" />
      </el-form-item>
      <el-form-item :label="$t('site.attributes.subTitle')" prop="subTitle">
        <el-input v-model="form.subTitle" />
      </el-form-item>
      <el-form-item :label="$t('attributes.email')" prop="email">
        <el-input v-model="form.email" />
      </el-form-item>
      <el-form-item :label="$t('attributes.password')" prop="password">
        <el-input type="password" v-model="form.password" />
      </el-form-item>
      <el-form-item :label="$t('attributes.passwordConfirmation')" prop="passwordConfirmation">
        <el-input type="password" v-model="form.passwordConfirmation" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        <el-button @click="resetForm('form')">{{$t("buttons.reset")}}</el-button>
      </el-form-item>
    </el-form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  data () {
    return {
      form: {
        title: '',
        subTitle: '',
        email: '',
        password: '',
        passwordConfirmation: ''
      }
    }
  },
  computed: {
    rules () {
      var password2 = (rule, value, callback) => {
        if (value !== this.form.password) {
          callback(new Error(this.$i18n.t('helpers.passwordConfirmation')))
        } else {
          callback()
        }
      }
      return {
        email: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' },
          { type: 'email', message: this.$t('helpers.bad-email'), trigger: 'change' }
        ],
        title: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        subTitle: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        password: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' },
            { min: 6, max: 32, message: this.$t('helpers.password'), trigger: 'change' }
        ],
        passwordConfirmation: [
          { required: true, message: this.$i18n.t('helpers.not-empty'), trigger: 'change' },
          { validator: password2, trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/install', this.form)
            .then(function (rst) {
              this.$message.success(this.$t('success'))
              this.$router.push({name: 'auth.users.sign-in'})
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    },
    resetForm (formName) {
      this.$refs[formName].resetFields()
    }
  }
}
</script>
