// by-react/src/plugins/site/admin/Info.jsx
import React, {Component} from 'react'
import { Form, Input, message} from 'antd'
import i18n from 'i18next'

import Layout from '../../../layouts/Dashboard'
import {Submit, formItemLayout} from '../../../form'
import {post, get} from '../../../ajax'

const FormItem = Form.Item

class WidgetF extends Component {
  componentDidMount () {
    const {setFieldsValue} = this.props.form
    get('/site/info').then(
      function (rst){
        setFieldsValue({
          title: rst.title,
          subTitle: rst.subTitle,
          keywords: rst.keywords,
          description: rst.description,
          copyright: rst.copyright,
        })
      }
    )
  }

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((err, values) => {
      if (!err) {
        post('/admin/site/info', values).then((rst) => {
          message.success(i18n.t('success'));
        }).catch(message.error)
      }
    });
  }

  render() {
    const { getFieldDecorator } = this.props.form;

    return (
    <Layout  breadcrumb={[{label: 'site.admin.info.title', href: '/site/admin/info'}]}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.title')}
          hasFeedback
        >
          {getFieldDecorator('title', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.subTitle')}
          hasFeedback
        >
          {getFieldDecorator('subTitle', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.keywords')}
          hasFeedback
        >
          {getFieldDecorator('keywords', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.description')}
          hasFeedback
        >
          {getFieldDecorator('description', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input type="textarea" rows={6}/>
          )}
        </FormItem>
        <FormItem
          {...formItemLayout}
          label={i18n.t('site.attributes.copyright')}
          hasFeedback
        >
          {getFieldDecorator('copyright', {
            rules: [{
              required: true, message: i18n.t('helpers.not-empty'),
            }],
          })(
            <Input />
          )}
        </FormItem>
        <Submit />
      </Form>
    </Layout>
    );
  }
}

const Widget = Form.create()(WidgetF);

export default Widget

// by-iview/src/plugins/site/admin/site/Info.vue
<template>
  <dashboard-layout admin>
    <group label-width="4.5em" label-margin-right="2em" label-align="right">
      <x-input
        required
        :title="$t('site.attributes.title')"
        :placeholder="$t('placeholders.not-empty')"
        v-model="form.title" />
      <x-input
        required
        :title="$t('site.attributes.subTitle')"
        :placeholder="$t('placeholders.not-empty')"
        v-model="form.subTitle" />
      <x-input
        required
        :title="$t('site.attributes.keywords')"
        :placeholder="$t('placeholders.not-empty')"
        v-model="form.keywords" />
      <x-textarea
        required
        :title="$t('site.attributes.description')"
        :placeholder="$t('placeholders.not-empty')"
        v-model="form.description" />
      <x-input
        required
        :title="$t('site.attributes.copyright')"
        :placeholder="$t('placeholders.not-empty')"
        v-model="form.copyright" />
    </group>
    <box gap="10px 10px">
      <x-button type="primary" @click.native="submitForm">{{$t("buttons.submit")}}</x-button>
    </box>
  </dashboard-layout>
</template>

<script>
import { Group, Box, XInput, XTextarea, XButton } from 'vux'
import { get, post, fail, success } from '@/ajax'

export default {
  components: {
    Group,
    XInput,
    XButton,
    Box,
    XTextarea
  },
  created () {
    get('/site/info').then((rst) => { this.form = rst }).catch((err) => fail(this, err))
  },
  data () {
    return {
      form: {
        title: '',
        subTitle: '',
        keywords: '',
        description: '',
        copyright: ''
      }
    }
  },
  methods: {
    submitForm () {
      post('/admin/site/info', this.form)
      .then(res => success(this))
      .catch(err => fail(this, err))
    }
  }
}
</script>
