// dashboard/src/plugins/site/admin/Cards.vue
<template>
  <dashboard-layout title="site.admin.cards.index.title" admin>
    <el-col :md="{span: 22, offset: 1}">
      <el-dialog :title="$t('buttons.edit')" :visible.sync="dialogFormVisible">
        <el-form ref="form" :model="form" :rules="rules" label-width="80px">
        <el-form-item :label="$t('attributes.loc')">
          <el-select v-model="form.loc">
            <el-option :key="i" :label="i" :value="i" v-for="i in ['carousel', 'zone']" />
          </el-select>
        </el-form-item>
          <el-form-item :label="$t('attributes.title')" prop="title">
            <el-input v-model="form.title" />
          </el-form-item>
          <el-form-item :label="$t('attributes.summary')" prop="summary">
            <el-input type="textarea" v-model="form.summary" />
            <span>{{$t('helpers.markdown')}}</span>
          </el-form-item>
          <el-form-item :label="$t('attributes.href')" prop="href">
            <el-input v-model="form.href" />
          </el-form-item>
          <el-form-item :label="$t('attributes.logo')" prop="logo">
            <el-input v-model="form.logo" />
          </el-form-item>
          <el-form-item :label="$t('attributes.action')" prop="action">
            <el-input v-model="form.action" />
          </el-form-item>
          <el-form-item :label="$t('attributes.sortOrder')">
            <el-select v-model="form.sortOrder">
              <el-option :key="i" :label="i" :value="i" v-for="i in 10" />
            </el-select>
          </el-form-item>
        </el-form>
        <div slot="footer" class="dialog-footer">
          <el-button @click="dialogFormVisible = false">{{$t("buttons.cancel")}}</el-button>
          <el-button type="primary" @click="handleSave('form')">{{$t("buttons.ok")}}</el-button>
        </div>
      </el-dialog>

      <el-button @click="handleEdit(null)" type="info" size="mini" icon="plus"/>

      <el-table :data="items" border stripe style="width: 100%;">
        <el-table-column width="120" prop="loc" :label="$t('attributes.loc')" />
        <el-table-column width="120" prop="sortOrder" :label="$t('attributes.sortOrder')" />
        <el-table-column :label="$t('attributes.content')">
          <template scope="scope">
            <h3>
              {{scope.row.title}}
              <a :href="scope.row.href" target="_blank">
                {{scope.row.action}}
              </a>
            </h3>
            <img :src="scope.row.logo"/>
            <pre><code>{{scope.row.summary}}</code></pre>
          </template>
        </el-table-column>
        <el-table-column width="80" :label="$t('buttons.manage')">
          <template scope="scope">
            <el-button-group>
              <el-button @click="handleEdit(scope.row)" type="info" size="mini" icon="edit" />
              <el-button @click="handleRemove(scope.row.id)" type="danger" size="mini" icon="delete" />
            </el-button-group>
          </template>
        </el-table-column>
      </el-table>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get, post, _delete} from '@/ajax'

export default {
  created () {
    get('/cards').then((rst) => { this.items = rst }).catch(this.$message.error)
  },
  data () {
    return {
      items: [],
      form: {
        title: '',
        href: '',
        summary: '',
        type: '',
        logo: '',
        loc: '',
        action: '',
        sortOrder: 0
      },
      dialogFormVisible: false
    }
  },
  computed: {
    rules () {
      return {
        action: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        title: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        summary: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        logo: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        href: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    handleEdit (form) {
      this.form = form || {action: '', title: '', logo: '', summary: '', type: '', href: '', loc: 'carousel', sortOrder: 5}
      this.dialogFormVisible = true
    },
    handleRemove (id) {
      this.$confirm(
        this.$t('are-you-sure'),
        '',
        {
          confirmButtonText: this.$t('buttons.ok'),
          cancelButtonText: this.$t('buttons.cancel'),
          type: 'warning'
        }
      )
      .then(() => {
        _delete(`/cards/${id}`).then(function (rst) {
          this.$message.success('success')
          this.items = this.items.filter((o) => o.id !== id)
        }.bind(this)).catch(this.$message.error)
      })
      .catch(() => {})
    },
    handleSave (formName) {
      this.$refs[formName].validate((valid) => {
        const id = this.form.id
        if (valid) {
          post(id ? `/cards/${id}` : '/cards', Object.assign({}, this.form, {type: 'markdown'}))
            .then(function (rst) {
              this.items = this.items.filter((o) => o.id !== id)
              this.items.unshift(Object.assign({}, id ? this.form : rst))
              this.dialogFormVisible = false
              this.$message.success(this.$t('success'))
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    }
  }
}
</script>

// desktop/src/plugins/site/admin/cards/Index.jsx
import React, { Component } from 'react'
import { Table, Row, Col, Button, Popconfirm, message } from 'antd'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'
import PropTypes from 'prop-types'


import Layout from '../../../../layouts/Dashboard'
import {get, _delete} from '../../../../ajax'

class WidgetF extends Component {
  state = { items: []}
  componentDidMount () {
    get('/cards').then(
      function (rst){
        this.setState({items: rst})
      }.bind(this)
    ).catch(message.error)
  }
  handleRemove = (id) => {
    const {formatMessage} = this.props.intl
    _delete(`/cards/${id}`)
      .then((rst)=>{
        message.success(formatMessage({id: 'messages.success'}))
        var items = this.state.items.filter((it) => it.id !== id)
        this.setState({items})
      })
      .catch(message.error)
  }
  render() {
    const {push} = this.props
    const columns = [
      {
        title: <FormattedMessage id="attributes.loc"/>,
        dataIndex: 'loc',
        key: 'loc',
      },
      {
        title: <FormattedMessage id="attributes.sortOrder"/>,
        dataIndex: 'sortOrder',
        key: 'sortOrder',
      },
      {
        title: <FormattedMessage id="attributes.content"/>,
        key: 'content',
        render: (text, record) => (<div>{record.title}<br/>{record.logo}<br/>{record.href}<br/>{record.type}<br/>{record.summary}<br/>{record.action}</div>)
      },
      {
        title: <FormattedMessage id="buttons.manage"/>,
        key: 'manage',
        render: (text, record) =>(<span>
          <Button onClick={(e)=>push(record.href)} shape="circle" icon="eye" />
          <Button onClick={(e)=>push(`/admin/cards/edit/${record.id}`)} shape="circle" icon="edit" />
          <Popconfirm title={<FormattedMessage id="messages.are-you-sure"/>} onConfirm={(e) => this.handleRemove(record.id)}>
            <Button type="danger" shape="circle" icon="delete" />
          </Popconfirm>
        </span>)
      },
    ]

    return (
      <Layout admin breads={[{href: '/admin/cards', label: 'site.admin.cards.index.title'}]}>
        <Row>
          <Col>
            <Button onClick={(e)=>push('/admin/cards/new')} type='primary' shape="circle" icon="plus" />
            <Table bordered rowKey="id" columns={columns} dataSource={this.state.items} />
          </Col>
        </Row>
      </Layout>
    );
  }
}



WidgetF.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired,
}

const Widget = injectIntl(WidgetF)

export default connect(
  state => ({}),
  {push},
)(Widget)
