// by-vue/src/plugins/site/posts/Show.vue
<template>
  <application-layout>
    <el-col :md="{span:16, offset:4}">
      <h2>{{item.title}}</h2>
      <md2ht :body="item.body" />
    </el-col>
  </application-layout>
</template>

<script>
import {get} from '@/ajax'

export default {
  data () {
    return {
      item: {
        title: '',
        body: '',
        name: ''
      }
    }
  },
  created () {
    get(`/posts/0?name=${this.$route.params.name}`).then((rst) => { this.item = rst }).catch(this.$message.error)
  }
}
</script>

// desktop/src/plugins/site/posts/Show.jsx
import React, { Component } from 'react'
import {message} from 'antd'

import Layout from '../../../layouts/Application'
import {get} from '../../../ajax'
import Item from './Item'

class Widget extends Component {
  state = { item: {updatedAt: '', body: ''}}
  componentDidMount () {
    const {id} = this.props.match.params
    get(`/posts/${id}`).then((rst)=>this.setState({item:rst})).catch(message.error)
  }
  render() {
    const {id} = this.props.match.params
    const {item} = this.state
    return (
      <Layout breads={[{href: '/posts', label: 'site.posts.index.title'}, {href: `/posts/${id}`, label: 'buttons.show'}]}>
        <Item value={item}/>
      </Layout>
    );
  }
}

export default Widget;
