// dashboard/src/plugins/auth/users/ResetPassword.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { Form } from 'semantic-ui-react'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'

import Layout from '../NonSignIn'
import {Submit} from '../../../form'
import {post} from '../../../ajax'

class Widget extends Component{
  state = { password: '', passwordConfirmation: '' }

  handleChange = (e, { name, value }) => this.setState({ [name]: value })

  handleSubmit = e => {
    e.preventDefault()
    const {push, match} = this.props
    var data = new URLSearchParams()
    data.append('token', match.params.token)
    data.append('password', this.state.password)
    data.append('passwordConfirmation', this.state.passwordConfirmation)
    post('/users/reset-password', data).then((rst) => {
      alert(rst.message)
      push('/users/sign-in')
    }).catch(alert)
  }
  render() {
    const {password, passwordConfirmation} = this.state;
    return (
      <Layout title="auth.users.reset-password.title">
        <Form onSubmit={this.handleSubmit}>
          <Form.Input name='password' value={password} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.password"/>} />
          <Form.Input name='passwordConfirmation' value={passwordConfirmation} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.passwordConfirmation"/>} />
          <Submit />
        </Form>
      </Layout>
    )
  }
}


Widget.propTypes = {
  push: PropTypes.func.isRequired
}


export default connect(
  state => ({}),
  {push},
)(Widget)

// by-iview/src/plugins/auth/users/ResetPassword.vue
<template>
  <dashboard-layout>
    <group label-width="4.5em" label-margin-right="2em" label-align="right">
      <x-input
        type="password"
        :title="$t('attributes.password')"
        :placeholder="$t('placeholders.password')"
        v-model="form.password" />
      <x-input
        type="password"
        :title="$t('attributes.passwordConfirmation')"
        :placeholder="$t('placeholders.passwordConfirmation')"
        v-model="form.passwordConfirmation" />
    </group>
    <box gap="10px 10px">
      <x-button type="primary" @click.native="submitForm">{{$t("buttons.submit")}}</x-button>
    </box>
  </dashboard-layout>
</template>

<script>
import { Group, Box, XInput, XButton } from 'vux'
import { post, fail, success } from '@/ajax'

export default {
  components: {
    Group,
    XInput,
    XButton,
    Box
  },
  data () {
    return {
      form: {
        password: '',
        passwordConfirmation: ''
      }
    }
  },
  methods: {
    submitForm () {
      post('/users/reset-password', Object.assign({}, this.form, {token: this.$route.params.token}))
      .then(res => {
        this.$router.push({name: 'auth.users.sign-in'})
        success(this, this.$t('auth.users.reset-password.success'))
      })
      .catch(err => fail(this, err))
    }
  }
}
</script>
