// fly/src/plugins/site/admin/Info.vue
<template>
  <dashboard-layout title="site.admin.info.title" admin>
    <el-col :md="{span:16, offset:1}">
      <el-form ref="form" :model="form" :rules="rules" label-width="80px">
        <el-form-item :label="$t('site.attributes.title')" prop="title">
          <el-input v-model="form.title" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.subTitle')" prop="subTitle">
          <el-input v-model="form.subTitle" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.keywords')" prop="keywords">
          <el-input v-model="form.keywords" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.description')" prop="description">
          <el-input type="textarea" v-model="form.description" />
        </el-form-item>
        <el-form-item :label="$t('site.attributes.copyright')" prop="copyright">
          <el-input v-model="form.copyright" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        </el-form-item>
      </el-form>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get, post} from '@/ajax'

export default {
  data () {
    return {
      form: {
        title: '',
        subTitle: '',
        keywords: '',
        description: '',
        copyright: ''
      }
    }
  },
  created () {
    get('/site/info').then((rst) => { this.form = rst }).catch(this.$message.error)
  },
  computed: {
    rules () {
      return {
        title: [
          { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        subTitle: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        keywords: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        description: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ],
        copyright: [
            { required: true, message: this.$t('helpers.not-empty'), trigger: 'change' }
        ]
      }
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/admin/site/info', this.form)
            .then(function (rst) {
              this.$message.success(this.$t('success'))
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    }
  }
}
</script>

// desktop/src/plugins/site/admin/site/Info.jsx
import React, { Component } from 'react'
import { Form, Input, message } from 'antd';
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'

import Layout from '../../../../layouts/Dashboard'
import {formItemLayout} from '../../../../constants'
import SubmitButton from '../../../../components/SubmitButton'
import {post, get} from '../../../../ajax'

const FormItem = Form.Item;

class WidgetF extends Component {
  componentDidMount () {
    const {setFieldsValue} = this.props.form
    get('/site/info').then(
      function (rst){
        setFieldsValue({
          title: rst.title,
          subTitle: rst.subTitle,
          keywords: rst.keywords,
          description: rst.description,
          copyright: rst.copyright,
        })
      }
    ).catch(message.error)
  }
  handleSubmit = (e) => {
    e.preventDefault();
    const {formatMessage} = this.props.intl
    this.props.form.validateFieldsAndScroll((err, values) => {
     if (!err) {
       post('/admin/site/info', values)
        .then((rst) => {
          message.success(formatMessage({id: 'messages.success'}))
        }).catch(message.error)
     }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const { getFieldDecorator } = this.props.form;
    return (
      <Layout admin breads={[{href: '/admin/site/info', label: 'site.admin.info.title'}]}>
        <Form onSubmit={this.handleSubmit}>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="site.attributes.title"/>}
            hasFeedback
          >
          {getFieldDecorator('title', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="site.attributes.subTitle"/>}
            hasFeedback
          >
          {getFieldDecorator('subTitle', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="site.attributes.keywords"/>}
            hasFeedback
          >
          {getFieldDecorator('keywords', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="site.attributes.description"/>}
            hasFeedback
          >
          {getFieldDecorator('description', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input type="textarea"/>
          )}
          </FormItem>

          <FormItem
            {...formItemLayout}
            label={<FormattedMessage id="site.attributes.copyright"/>}
            hasFeedback
          >
          {getFieldDecorator('copyright', {
            rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
          })(
            <Input />
          )}
          </FormItem>

          <SubmitButton />
        </Form>
      </Layout>
    );
  }
}


WidgetF.propTypes = {
  intl: intlShape.isRequired,
}

export default Form.create()(injectIntl(WidgetF))
