// dashboard/src/plugins/site/admin/Seo.vue
<template>
  <dashboard-layout title="site.admin.seo.title" admin>
    <el-col :md="{span:16, offset:1}">
      <el-form ref="form" :model="form" :rules="rules" label-width="120px">
        <el-form-item :label="$t('site.admin.seo.googleVerifyCode')" prop="googleVerifyCode">
          <el-input v-model="form.googleVerifyCode" />
        </el-form-item>
        <el-form-item :label="$t('site.admin.seo.baiduVerifyCode')" prop="baiduVerifyCode">
          <el-input v-model="form.baiduVerifyCode" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t("buttons.submit")}}</el-button>
        </el-form-item>
      </el-form>
    </el-col>
    <el-col :md="{span:16, offset:3}">
      <ul class="list-group">
        <li :key="i" v-for="(l, i) in links">
          <a :href="`/${l}`" target="_blank">{{l}}</a>
        </li>
      </ul>
    </el-col>
  </dashboard-layout>
</template>

<script>
import {get, post} from '@/ajax'

export default {
  data () {
    return {
      form: {
        googleVerifyCode: '',
        baiduVerifyCode: ''
      }
    }
  },
  created () {
    get('/admin/site/seo').then((rst) => { this.form = rst }).catch(this.$message.error)
  },
  computed: {
    rules () {
      return {
      }
    },
    links () {
      return [
        'robots.txt',
        'sitemap.xml.gz',
        `google${this.form.googleVerifyCode}.html`,
        `baidu_verify_${this.form.baiduVerifyCode}.html`
      ].concat(this.$store.state.siteInfo.languages.map((l) => `rss-${l}.atom`))
    }
  },
  methods: {
    submitForm (formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          post('/admin/site/seo', this.form)
            .then(function (rst) {
              this.$message.success(this.$t('success'))
            }.bind(this)).catch(this.$message.error)
        } else {
          return false
        }
      })
    }
  }
}
</script>

// desktop/src/plugins/site/admin/site/Seo.jsx
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { Form, Row, Col, Input, message, Card } from 'antd';
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import { connect } from 'react-redux'

import Layout from '../../../../layouts/Dashboard'
import {formItemLayout} from '../../../../constants'
import SubmitButton from '../../../../components/SubmitButton'
import {post, get} from '../../../../ajax'

const FormItem = Form.Item;

class WidgetF extends Component {
  state = { googleVerifyCode:'', baiduVerifyCode: ''}
  componentDidMount () {
    const {setFieldsValue} = this.props.form
    get('/admin/site/seo').then(
      function (rst){
        setFieldsValue({
          googleVerifyCode: rst.googleVerifyCode,
          baiduVerifyCode: rst.baiduVerifyCode,
        })
        this.setState(rst)
      }.bind(this)).catch(message.error)
  }
  handleSubmit = (e) => {
    e.preventDefault();
    const {formatMessage} = this.props.intl
    this.props.form.validateFieldsAndScroll((err, values) => {
     if (!err) {
       post('/admin/site/seo', values)
        .then((rst) => {
          message.success(formatMessage({id: 'messages.success'}))
        }).catch(message.error)
     }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const { getFieldDecorator } = this.props.form;
    const {googleVerifyCode, baiduVerifyCode} = this.state
    const {languages} = this.props
    return (
      <Layout admin breads={[{href: '/admin/site/seo', label: 'site.admin.seo.title'}]}>
        <Row>
          <Col>
            <Form onSubmit={this.handleSubmit}>

              <FormItem
                {...formItemLayout}
                label={<FormattedMessage id="site.admin.seo.google.verifyCode"/>}
                hasFeedback
              >
              {getFieldDecorator('googleVerifyCode', {
                rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
              })(
                <Input />
              )}
              </FormItem>

              <FormItem
                {...formItemLayout}
                label={<FormattedMessage id="site.admin.seo.baidu.verifyCode"/>}
                hasFeedback
              >
              {getFieldDecorator('baiduVerifyCode', {
                rules: [{ required: true, message: formatMessage({id:"errors.not-empty"})}],
              })(
                <Input />
              )}
              </FormItem>

              <SubmitButton />
            </Form>
          </Col>
          <Col md={{offset:4, span:8}}>
            <Card>
              <ul>
                {(languages.map((l)=>`rss-${l}.atom`).concat(['robots.txt', 'sitemap.xml.gz', `google${googleVerifyCode}.html`, `baidu_verify_${baiduVerifyCode}.html`])).map((l,i)=><li key={i}><a rel="noopener noreferrer" target="_blank" href={`/${l}`}>{l}</a></li>)}
              </ul>
            </Card>
          </Col>
        </Row>
      </Layout>
    );
  }
}


WidgetF.propTypes = {
  intl: intlShape.isRequired,
  languages: PropTypes.array.isRequired,
}

const Widget = Form.create()(injectIntl(WidgetF))


export default connect(
  state => ({
    languages: state.siteInfo ? state.siteInfo.languages : [],
  }),
  {},
)(Widget)
